# La micromobilitat en temps de pandèmia

###### Daniel Albalate *(Universitat de Barcelona)* {-}
###### Carlos León-Gómez *(Universitat de Barcelona)* {-}

## Introducció

La pandèmia de la COVID-19 ha comportat grans transformacions econòmiques, socials i de mobilitat. L’arribada d’una amenaça per a la salut pública i per a la salut individual, com ho és la gran transmissibilitat del virus SARS-CoV-2, va generar ràpidament modificacions profundes en els patrons de mobilitat, que no s’han revertit totalment i que amenacen de tenir un cert efecte permanent i estructural. D’una banda, les mesures restrictives de la mobilitat, adoptades per les autoritats amb l’objectiu de limitar els contagis, i de l’altra, la por del contagi i la percepció de risc dels usuaris de la mobilitat compartida, especialment del transport col·lectiu, van afectar greument la demanda de mobilitat, així com la demanda específica del transport col·lectiu, i en conseqüència el seu finançament. No obstant això, alguns modes de transport, com ara el transport privat i la micromobilitat, van guanyar un cert atractiu. El segon cas, objecte d’aquest capítol, la micromobilitat, facilitada per vehicles d’ús individual, permetia una mobilitat de curta distància amb un risc de contagi escàs. La flexibilitat i el baix cost operatiu, de manteniment i d’adquisició, d’aquesta opció van facilitar-ne un increment.

En aquest capítol, pretenem revisar la literatura que ha analitzat el paper de la micromobilitat durant i després de la pandèmia per COVID-19. D’aquesta manera, esperem poder entendre millor el paper substitutiu de la micromobilitat en relació amb els grans modes de transport (el transport privat i el transport públic), el paper que pot tenir aquesta micromobilitat per aconseguir objectius clau de les grans ciutats en relació amb la sostenibilitat de la seva mobilitat, i els factors que promouen i afavoreixen una adopció més gran d’aquests modes de transport. 

Per assolir aquests objectius, el capítol s’organitza de la manera següent. En primer lloc, es presenta la micromobilitat com a mode alternatiu als altres grans modes de transport, com ara el transport en vehicle privat (essencialment cotxes i motocicletes de gran cilindrada) i el transport públic, i se’n mostra la tendència recent. En segon lloc, s’analitza l’efecte de la pandèmia en la demanda i oferta de la micromobilitat, amb un èmfasi especial en els efectes substitutius o complementaris d‘aquesta mobilitat respecte del transport privat. En tercer lloc, s’observa el paper de la micromobilitat davant de les transformacions econòmiques i socials causades per la pandèmia (com ara el teletreball, la desigualtat i els efectes potser més permanents del que es preveia) sobre patrons de mobilitat menys sostenibles com ara l’ús del transport privat. En quart lloc, es presenten evidències sobre les vies d’inducció de la demanda de micromobilitat i en cinquè lloc, les estratègies d’oferta de serveis de micromobilitat compartida que han promogut algunes ciutats. Finalment, el capítol acaba amb unes conclusions breus.

## La micromobilitat a les ciutats

Tot i que no hi ha una única definició sobre els modes de transport que conformen la micromobilitat, en general es considera que formen part d’aquest segment les formes de transport (vehicles) de baix pes i velocitat, i que solen ser d’ús individual. De fet, molts dels modes de transport considerats dins d’aquest grup s’anomenen també *vehicles de mobilitat individual o personal*. Entre les diverses definicions, trobem, per exemple, la del Fòrum Internacional de Transport [-@micromobility2020], que defineix els vehicles que conformen la micromobilitat com aquells que tenen un pes no superior als 350 kg (771 lliures) i una velocitat de disseny no superior a 45 km/h^[Aquest capítol, però, prendrà la classificació de micromobilitat tipus A i tipus C, que conformen els modes de transport inferiors a 35 kg i amb velocitat no superior a 45 km/h.].  Entre aquests vehicles hi ha els propulsats per humans (com ara les bicicletes i els patinets no elèctrics) i els vehicles amb subministrament elèctric (com ara les bicicletes elèctriques, els escúters elèctrics i els patinets autoequilibrats), ja siguin de propietat privada o compartida.

La micromobilitat és un mode de transport alternatiu en la curta distància i, per tant, actua de substitut, sobretot en aquestes distàncies curtes, per la qual cosa pot contribuir a generar ciutats més habitables, amb menys congestió, i nivells reduïts de contaminació atmosfèrica i acústica, si és capaç d’atreure viatges dels modes que generen aquestes externalitats negatives (Oeschger, Carroll i Caulfield, [-@Oeschger2020]). L’atractiu principal de la micromobilitat és que aporta una alternativa de mobilitat flexible, sostenible, rendible i «a demanda» (Shaheen et al., [-@Shaheen2020]). Actualment és adoptada àmpliament per passatgers que recorren regularment distàncies menors de 5 km, la qual cosa representa un $50\%$-$60\%$ del total de passatgers/km recorreguts a la Xina, els Estats Units o la Unió Europea (Heineke et al., [-@Heineke2019]; Scurtu, [-@Scurtu2019]), una distància que es podria incrementar amb infraestructures més adequades. 

Segons la literatura recent, la micromobilitat ha ajudat a afrontar un nombre significatiu de reptes en el transport i la mobilitat de les ciutats. Ha contribuït a reduir la congestió, a combatre la desigualtat en l’accés als serveis i les oportunitats, i s’ha mostrat com una força positiva en el desenvolupament d’una mobilitat més ecològica i sostenible per ajudar les ciutats a complir els seus objectius ambientals (Abduljabbar et al., [-@Abdul2021]).

En els darrers anys, amb els avenços en la indústria de les tecnologies de la informació i la tecnologia mòbil, i l’avenç de l’economia compartida o col·laborativa, la micromobilitat ha guanyat popularitat com a mode de transport a les grans ciutats (Kaufman i Buttenwieser, [-@Kaufman2018]). Per aquest motiu, moltes grans ciutats han promogut esquemes col·laboratius a partir de la micromobilitat com a mesura per a una mobilitat urbana més sostenible (Fong, [-@Fong2019]). Això ha fet que, quan va arribar la pandèmia, ja hi haguessin els fonaments i una primera base operativa d’oferta que pogués servir una demanda que, amb la pandèmia, ha viscut un increment notable que ha posat de manifest el rol que aquesta mobilitat pot tenir a les grans ciutats.

## La micromobilitat com a alternativa durant i després de la pandèmia

Una característica dels sistemes de micromobilitat en el context urbà és que proporcionen una solució de transport de curta distància, en què s’inclouen els transports de primer-últim quilòmetre, quan es conjuguen amb sistemes de transport públic. En aquest sentit, la micromobilitat proporciona una solució de transport porta a porta que pot arribar a competir amb els automòbils (Kager, Bertolini i Te Brömmelstroet, [-@Kager2016]). Tot i això, la pandèmia sembla haver canviat aquest component de curta distància de la micromobilitat, o haver-lo matisat, ja que hi ha dades que durant la pandèmia l’ús de la micromobilitat compartida, específicament de la bicicleta, es va incrementar en la distància mitjana recorreguda, a ciutats com Nova York, Boston i Chicago, als Estats Units d’Amèrica (Padmanabhan et al., [-@Padmanabhan2021]).

Les dades mostren com la pandèmia s’ha associat de manera generalitzada amb una caiguda estrepitosa de l’ús dels mitjans de transport públic, així com amb un major ús dels modes de micromobilitat en certes àrees. Si bé aquesta caiguda era esperable, atès que la majoria dels governs van implementar mesures d’aïllament social de manera obligatòria, és interessant observar que, fins i tot en països on aquestes mesures no van ser obligatòries, sinó voluntàries, com és el cas de Suècia, la reducció en la demanda de transport públic va caure entre el $40\%$ (Västra Götaland) i el $60\%$ (Estocolm i Skåne), mentre que l’ús de la bicicleta no va mostrar una tendència a la baixa en zones urbanes i es va incrementar a les zones suburbanes (Jenelius i Cebecauer, [-@Jenelius2020]). Fins i tot, s’ha documentat, a partir d’una enquesta de percepció sobre els usuaris del transport ferroviari a la Xina, que entre els viatgers que van renunciar a l’ús del transport ferroviari per por de ser contagiats, el $40\%$ de les persones enquestades pensava substituir el seu mitjà de transport habitual per un vehicle privat, el $21\%$ per viatges a peu, el $36\%$ per bicicleta o vehicles elèctrics, i només un $3\%$ per altres modes de transport com ara el taxi o el bus. Per tant, la majoria ($57\%$) pensava optar per un mitjà diferent del vehicle privat, amb un augment significatiu dels viatges en modes propis de la micromobilitat.

Per dimensionar el potencial que pot tenir aquesta migració d’usuaris a altres mitjans de transport, cal esmentar la gravetat de la caiguda de l’ús del transport públic. En aquest sentit, i fent servir dades del Report de Mobilitat de Google entre febrer i maig de 2020 (és a dir, durant la primera onada de la pandèmia), Zhang, Hayashi i Frank [-@Zhang2021] reporten que, a nivell global, la caiguda de l’ús del transport públic va ser d’un $28,3\%$. Per ser exactes, a escala estatal aquesta caiguda va ser del $53,4\%$ (màx. $76,7\%$ a l’abril) a Itàlia; $51,7\%$ (màx. $80,9\%$ a l’abril) a Espanya; $49,7\%$ (màx. $78,4\%$ a l’abril) a França; $39,5\%$ (màx. $62,3\%$ a l’abril) al Regne Unit; $38,9\%$ (màx. $57,1\%$) al Brasil; $36\%$ (màx. $55,6\%$ a l’abril i $55,7\%$ al maig) a Mèxic; $32,4\%$ (màx. $59,9\%$ a l’abril) a l’Índia; $31,1\%$ ($48,1\%$ a l’abril) a Alemanya; $29,3\%$ (màx. $43,2\%$ al maig) al Japó; $24,5\%$ (màx. $48,6\%$ a l’abril) a Rússia; $21,6\%$ (màx. $31,3\%$ a l’abril) a Suècia; $15,8\%$ (màx. $31,1\%$) als Estats Units d’Amèrica; i $12,9\%$ (màx. $20\%$ a l’abril) a Corea del Sud. 

De fet, segons els experts enquestats per Zhang, Hayashi i Frank [-@Zhang2021], s’espera que la caiguda en l’ús del transport públic sigui substituïda per l’ús d’altres modes de transport personal. En particular, la taula \@ref(tab:tab4c1) ens mostra com la majoria d’especialistes coincideixen que el canvi modal cap als automòbils és el més probable ($65\%$), seguit dels viatges a peu ($42\%$), amb bicicleta ($36\%$) i motocicleta ($20\%$). El canvi cap als automòbils és particularment pronunciat a la Xina ($79\%$) i a Corea del Sud ($94\%$), mentre que una gran part dels especialistes coincideixen que els països europeus poden transitar cap a un sistema de transport cada cop més respectuós amb el medi ambient mitjançant l’ús de les bicicletes ($58\%$).

```{r tab4c1, echo=FALSE, warning=FALSE, results = 'asis', message=FALSE}
library(knitr)
library(dplyr)
library(kableExtra)
a<-c("**Xina**","**Europa**","**EUA / Canadà**","**Altres (Àsia)**","**Japó**","**Índia**","**Corea del Sud**","**Altres**","**Tots els països / Regions**")
b<-c("79%", "68%", "63%", "52%", "52%","46%","94%","60%","65%")
c<-c("44%", "60%", "40%", "30%", "26%","50%","33%","40%","42%")
d<-c("38%", "58%", "40%", "30%", "23%","25%","6%","36%","36%")
e<-c("20%", "10%", "3%", "49%", "3%","50%","0%","28%","20%")
f<-c("13%", "24%", "29%", "24%", "32%","29%","0%","20%","23%")
matrix<-matrix(c(a,b,c,d,e,f),ncol=6,byrow=F)
kable(matrix,col.names=c("De transport públic a:","Automòbil","A peu","Bicicleta","Motocicleta","Altres"),caption="Canvi modal observat pels especialistes",align=c("l","c","c","c","c","c"),booktabs=T) %>%
  footnote(general = " Zhang, Hayashi i Frank [-@Zhang2021])", general_title = "Font:", footnote_as_chunk = T)
```

## La micromobilitat davant de les transformacions econòmiques, socials i laborals

La pandèmia ha promogut grans transformacions econòmiques, socials i laborals. Una de les més destacables ha estat l’augment del teletreball o de formes laborals més flexibles, que tenen necessàriament un impacte sobre la demanda de transport. En efecte, la pandèmia i les mesures d’aïllament social aplicades pels governs van accelerar la implementació del teletreball, que es va accentuar a causa de la preocupació creixent per la inseguretat dels espais molt concorreguts (Vickerman, [-@Vickerman2021]), per la qual cosa els seus efectes sobre els patrons de mobilitat, i en concret sobre l’ús i l’adopció de la micromobilitat, podrien ser en certa mesura permanents (Van Wee i Witlox, [-@Van2021]).

Per exemple, hi ha dades que la pandèmia ha generat un canvi en els hàbits de teletreball i compres en línia, sobretot en individus que abans de la pandèmia feien aquestes activitats de manera presencial. En particular, Shamshiripour, Rahimi, Shabanpour i Mohammadian [-@Shamshiripour2020] mostren que, en el cas de Chicago, les persones que no havien teletreballat mai van passar d’un $71\%$ a un $37\%$, mentre que les persones que treballaven des de casa 5 dies o més a la setmana van passar d’un $15\%$ a un $48\%$; és a dir, pràcticament la totalitat d’individus que no havien estat exposats mai al teletreball van haver d’adoptar-lo a causa de la pandèmia ($33\%$). No obstant això, és interessant constatar que el $37\%$ dels individus, principalment treballadors de primera línia o de la indústria de serveis, no van poder migrar cap a aquesta modalitat de treball, la qual cosa mostra els límits del teletreball. Encara més, la proporció de persones que van comprar provisions per primera vegada va passar d’un $20\%$ abans de la pandèmia a un $33\%$ després de la pandèmia. I les persones que feien compres de menjar en línia a restaurants, que representava el $42\%$ abans de la pandèmia, va passar al $55\%$ després de la pandèmia. 

Tot i que l’ús total de la micromobilitat va experimentar una reducció causada principalment per la reducció del trànsit en les hores punta, la pandèmia també va generar un efecte diferenciat entre la motivació del viatge i l’ús dels diferents modes de micromobilitat. Per exemple, a Zuric (Suïssa) hi ha certs indicis que suggereixen que, durant el període d’aïllament, la proporció d’activitats relacionades amb la llar, el parc i les compres al supermercat va augmentar la demanda de micromobilitat, mentre que la proporció d’activitats relacionades amb l’oci i altres compres va disminuir-ne la demanda (Li, Zhao, Haitao, Mansourian i Axhausen, [-@Li2021]). 

També s’ha observat que les ciutats de baixa densitat són les que més van incrementar l’ús del transport de micromobilitat. Usant dades de les rutes de vianants/bicicletes a onze ciutats dels Estats Units, Zhang i Fricker [-@Zhang2021b] demostren que l’impacte de la COVID-19 en l’ús del transport no motoritzat (p. ex., bicicletes i caminades) és positiu en ciutats amb poca densitat poblacional (p. ex. Indianapolis, Clovis, Charlotte i Tallahassee), negatiu en ciutats amb alta densitat (p. ex., San Francisco, Long Beach, New York City i Boston) i mixt en dues ciutats (Washington i Seattle). 

Pels motius assenyalats anteriorment, la transició del transport públic cap a modalitats com la bicicleta o el vehicle privat no es pot explicar per un sol factor aïllat, sinó per un conjunt de factors. En aquest sentit, la substitució modal té uns límits. En particular, Schaefer, Tuitjer i Levin-Keitel [-@Schaefer2021] documenten per al cas de Hannover (Alemanya) que, si bé la caiguda en l’ús del bus i del tren lleuger és absorbida per un major ús de la bicicleta i el vehicle privat, aquesta relació no es manté en el cas del tren, en què la bicicleta actua més com un mode complementari, en comptes de substitut. A més, l’estudi demostra que tenir consciència a favor del medi ambient promou la transició cap a les bicicletes, mentre que dificulta la transició cap als vehicles privats, per la qual cosa campanyes de conscienciació mediambiental podrien contribuir a promoure la transició cap a modes de transport més nets, i dificultar la transició cap a modes més contaminants.

## Els factors d'inducció de la demanda de micromobilitat 

Dins dels factors que promouen la transició, o substitució modal, n’hi ha de psicològics, com ara la percepció de la COVID-19 i de l’eficàcia de les mesures d’aïllament social implementades pels governs. Per exemple, les persones més conscienciades de les complicacions que pot tenir la malaltia tendeixen a prioritzar els modes de transport personal per sobre dels modes de transport públic. En canvi, si la percepció és que les mesures implementades pels governs són prou estrictes, es genera una influència positiva sobre l’ús del transport públic i els sistemes de transport no motoritzats, com ara la bicicleta (Aaditya i Rahul, [-@Aaditya2021]).

Si bé els factors psicològics tenen un paper molt important en el canvi modal, no tots els individus tenen la mateixa possibilitat de canviar d’un mode a un altre de manera tan senzilla. En aquest sentit, la pandèmia ha afectat els individus de manera desigual. En particular, les persones amb nivells d’ingressos més baixos, menys educació i que viuen més allunyades del lloc de treball (normalment relacionats amb els grups de menys ingressos) són aquelles en què la pandèmia ha tingut un efecte menor en la seva demanda de transport. Així ho han confirmat alguns estudis fets en determinades ciutats, o enquestes d’àmbit internacional. En el cas d’Estocolm, per exemple, els usuaris que viuen en els barris amb nivells d’ingressos o educació baixos van patir una caiguda menys pronunciada en l’ús del transport públic respecte dels usuaris de barris amb nivells d’ingressos més alts (Almlöf, Rubensson, Cebecauer i Jenelius, [-@Almlof2021]).

La situació és semblant en el cas de l’Àrea Metropolitana de Barcelona, en què els individus del grup amb menys ingressos amb prou feines van modificar el nombre de viatges, mentre que els individus del grup amb ingressos mitjans-alts van reduir-ne el nombre respecte a l’any 2019. Això es pot explicar perquè és precisament el grup d’individus amb ingressos baixos el que possiblement s’associï amb els treballadors anomenats de *primera línia*, per als quals el teletreball no és una opció viable (Mejía-Dorantes, Montero i Barceló, [-@Mejia2021]). Així mateix, Dingil i Esztergár-Kiss [-@Dingil2021] esmenten que la distància del viatge i el nivell d’ingressos són els factors que més influencien la presa de decisions sobre el canvi modal, ja que els individus que recorrien una distància més gran i percebien el nivell d’ingressos més baix van considerar que el canvi a altres modes de transport diferents del transport públic no era factible.

El gènere també és un factor que té un paper important en el moment de facilitar la transició cap a modes de micromobilitat. Això s’explica perquè els viatges que fan els homes i les dones són en certa mesura diferents. Sense anar més lluny, en viatges amb individus relativament comparables la preferència per fer certes activitats mitjançant una modalitat o una altra és reveladora. Per exemple, una enquesta en què s’inclouen individus de diferents països d’Europa va revelar que els homes preferien fer els trajectes per anar a comprar al supermercat amb bicicleta, mentre que les dones preferien caminar (Carboni, Costa, Kalakou i Pirra, [-@Carboni2021]).

## Els sistemes compartits de micromobilitat i el seu rol en la pandèmia

Recentment, han tingut un paper rellevant altres modalitats de micromobilitat, com ara els modes de transport compartit. Si bé l’auge d’aquest mode de transport va tenir lloc poc abans de la pandèmia, el seu avantatge rau en la possibilitat d’accedir-hi des de qualsevol telèfon intel·ligent. De fet, la micromobilitat compartida (és a dir, escúters elèctrics, bicicletes, bicicletes elèctriques, ja siguin compartides en estacions d’emmagatzematge o fora) va arribar gairebé als 136 milions de viatges als Estats Units l’any 2019, xifra que va representar un increment del $60\%$ respecte del seu ús el 2018 (NACTE, [-@Nacto2020])^[La mitjana del viatge en aquests modes de micromobilitat va ser d’11-12 minuts i 1-1,5 milles.].  

A més de ser una alternativa de transport de curta distància, normalment els escúters elèctrics s’associen a modes de transport més respectuosos amb el medi ambient. Per exemple, a París (França), la companyia Lime va estimar que l’ús dels escúters elèctrics va substituir 1,2 milions de viatges en vehicles automotors (cosa que representa prop de 330 tones de CO2), mentre que a Munic (Alemanya) un programa pilot va mostrar que el $60\%$ dels viatges diaris en cotxe es podrien substituir per escúters elèctrics. Com en el cas de les bicicletes, l’ús d’aquesta modalitat de transport també es pot associar a una conscienciació mediambiental més gran. Per exemple, a Brussel·les (Bèlgica), una enquesta va mostrar que el $25\%$ de les persones que utilitzen escúters elèctrics ho fan perquè consideren que ajuda a reduir la contaminació atmosfèrica (Dies, Arsenio i Ribeiro, [-@Dias2021]). 

Amb la finalitat d’evitar la transició del transport públic cap als vehicles privats, diverses ciutats han implementat polítiques públiques per promoure l’ús de la micromobilitat entre els viatgers freqüents. En concret, Dies, Arsenio i Ribeiro [-@Dias2021] esmenten alguns casos documentats arreu del món. Per exemple, a Rotterdam (Països Baixos), en plena pandèmia, es va establir una aliança amb diferents proveïdors de serveis per assegurar la disponibilitat de 1.500 bicicletes i més de 1.500 escúters elèctrics en més de 25 punts estratègics de transport públic a la ciutat. A Milà (Itàlia) es van alliberar alguns carrils viaris per promoure l’ús de la micromobilitat, es van ampliar les voreres i es van fer diferents connexions amb carrils bici, entre altres mesures de planejament urbanístic. Per part seva, alguns proveïdors de serveis de micromobilitat van prendre la iniciativa d’oferir serveis gratuïts durant la pandèmia. Per exemple, en algunes localitats dels Estats Units (Denver, Los Angeles, San Diego, Santa Monica i Washington) companyies com ara Lyft van oferir trenta minuts de viatge gratuït amb els seus escúters elèctrics als treballadors de *primera línia*. En altres ciutats com ara Nova York, Chicago, Boston i San Francisco, també es va oferir l’abonament gratuït del programa de bicicletes compartides. I en algunes ciutats d’Europa, altres companyies com Bird van oferir escúters gratuïts a voluntaris de la Creu Roja per poder donar resposta a les crides d’emergència.

Malgrat que calen més dades, s’ha explorat la factibilitat d’implementar sistemes d’escúters elèctrics com a part del sistema de transport públic a certes ciutats com Riad, a l’Aràbia Saudita. En particular, a partir d’una enquesta duta a terme l’abril del 2020, la majoria de les persones enquestades coincidien que estaven disposades a fer servir aquest mode de micromobilitat com a mitjà de transport públic (els homes hi estaven gairebé dues vegades més disposats que les dones). Sembla que factors com ara l’edat, el gènere i l’ús anterior d’algun sistema de servei compartit (p. ex. Uber) són importants per estar disposat a utilitzar escúters elèctrics. Ara bé, altres factors com una infraestructura insuficient, el clima i la seguretat viària són els obstacles més importants per implementar-los (Almannaa, Alsahhaf, Ashqar i Elhenawy, [-@Almannaa2021]). 

D’aquesta manera, per poder aconseguir una transició cap a ciutats més sostenibles, cal promoure l’ús d’esquemes de micromobilitat com a alternativa als vehicles privats. De fet, en molts països del món ja s’ha pres la iniciativa de fer servir la pandèmia i les mesures d’aïllament social per trobar un consens polític i introduir mesures de redisseny viari. Per exemple, Combs i Pardo [-@Combs2021] documenten 1.313 accions implementades al món per diferents nivells de govern, el $64\%$ de les quals estan enfocades a expandir els espais d’ús per a ciclistes o per a vianants, modificar la legislació per incrementar els drets dels ciclistes i proporcionar millors condicions d’aparcament de bicicletes, entre altres accions. Tot i això, moltes d’aquestes mesures no sempre són populars, sobretot entre els segments de població habituats als vehicles privats, o que en són propietaris, encara que aquesta actitud sembla que està canviant. Per exemple, en una enquesta feta a Espanya, gairebé tres quartes parts de la població donaven suport a mesures que buscaven restringir l’ús del vehicle, o incrementar els espais i les vies de trànsit per a ciclistes o vianants, tot i que, certament, la contundència del suport era reduïda entre els participants amb nivells d’ingressos més elevats i que eren propietaris d’un vehicle particular (Awad-Nunez, Juliol, Moya-Gomez i Gomez, [-@Awad2021]).

Encara que les mesures de redisseny urbà plantegen una solució per a la sostenibilitat de les ciutats a llarg termini, implementar-les no acostuma a ser l’opció més convenient a curt termini. De fet, hi ha mesures més senzilles que es poden implementar ràpidament amb la finalitat de generar confiança en els usuaris de modes de transport compartit. Aquestes mesures estan relacionades amb incrementar el sanejament de la infraestructura de transport amb accions com ara desinfectar periòdicament les manetes i els seients dels passatgers, o proveir de tovalloles desinfectants els usuaris del transport, entre d’altres.

Tot i això, aquestes mesures menors encara requereixen un finançament que difícilment pot ser del tot públic. És per això que resulta indispensable conèixer la disponibilitat que es té per pagar per aquestes mesures sanitàries i la disponibilitat d’ús dels usuaris dels diferents sistemes de transport. Amb aquests dos aspectes presents, Awad-Núñez, Julio, Gomez, Moya-Gomez i Sastre [-@Awad2021b] van fer una enquesta a Espanya. Van observar que gairebé el $90\%$ dels usuaris del transport públic prenen en consideració de tornar a utilitzar-ne els serveis en l’època post-COVID-19, i el $64\%$ estaria disposat a pagar més si els operadors incrementessin les mesures de sanejament. Pel que fa a aquestes mesures, el $70,6\%$ de les persones entrevistades va assenyalar que s’havien d’orientar a incrementar l’oferta de transport per evitar la congestió (tot i que només el $53\%$ estava disposat a pagar més), mentre que el $52,1\%$ va respondre que les mesures havien d’incrementar la neteja i la higienització d’aquests espais (amb un $40\%$ disposat a pagar més per aquesta mesura). També van detectar que la disponibilitat dels usuaris per utilitzar sistemes compartits de bicicletes o escúters elèctrics se situa al voltant del $68\%$, amb només el $36\%$ disposat a pagar més per les diferents mesures sanitàries. En particular, entre les més importants, el $51\%$ de les persones enquestades va esmentar que calia enfocar les mesures a posar cobertes d’un sol ús a les manetes (amb un $36\%$ disposat a pagar més per aquesta mesura), i el $38\%$ va opinar que els operadors havien de proveir-los de màscares, gel desinfectant i guants (amb un $27,5\%$ disposat a pagar més).

Finalment, en el moment de prendre en consideració quin mode de micromobilitat convé de promoure, és útil tenir en compte que se n’han adoptat de diferents en funció de l’objectiu del transport. En aquest sentit, Li, Zhao, Haitao i Axhausen [-@Li2020] mostren que, en el cas de Zuric (Suïssa), dels sistemes compartits de micromobilitat sense estació (*dockless*), les bicicletes s’han utilitzat principalment en viatges des de l’estació fins a casa, i els escúters elèctrics per a viatges relacionats amb activitats recreatives; mentre que els sistemes compartits de micromobilitat amb estació (*docked*) s’han utilitzat per dirigir-se a una estació de transport públic, a parcs i a botigues de queviures. D’aquesta manera, independentment de l’impacte d’aquestes activitats a causa de la pandèmia, el propòsit del viatge és un factor important a tenir en compte en el disseny de polítiques públiques que busquin promoure diferents modes de micromobilitat.

## Conclusions 

Els efectes de la pandèmia sobre la mobilitat a les grans ciutats s’han concretat en una transformació dels patrons de mobilitat, una reconsideració de l’espai de les ciutats dedicat a la mobilitat, un canvi de les percepcions dels usuaris sobre els beneficis i els costos dels diferents modes de transport i, per tot això, una elecció modal diferent que pot mantenir-se amb el temps, malgrat el caràcter conjuntural de la pandèmia. Entre els modes de transport que s’han incrementat trobem l’anomenada *micromobilitat*, basada en vehicles i sistemes de mobilitat personal, de poc pes i baixa velocitat, d’ús eminentment individual –encara que en molts casos compartit– i que permet, especialment en trajectes curts, una mobilitat més segura davant del risc de contagi per la COVID-19. 
La revisió dels estudis i experiències esmentats en aquest capítol mostra com la pandèmia va comportar una acceleració de l’adopció d’aquesta micromobilitat, que ja es trobava en una tendència favorable en moltes ciutats, especialment europees. L’oferta pública de promoció de sistemes de micromobilitat compartida, amb la bicicleta com a principal mitjà, va ser capaç d’oferir una alternativa viable, flexible, barata i segura en un moment en què les ciutats es trobaven davant del difícil equilibri entre els riscos per a la salut pública i els beneficis econòmics que genera la mobilitat. Aquesta alternativa va oferir oportunitats de mobilitat i d’accessibilitat també als col·lectius de renda baixa que difícilment poden optar per una mobilitat en vehicle privat.

La micromobilitat, per les seves característiques, és un mode que pot competir tant amb el transport privat com amb el transport públic. No obstant això, atès el seu avantatge relatiu en el viatge porta a porta i en les distàncies curtes, té més facilitat de competir amb el transport públic. Aquesta capacitat es va poder comprovar durant la pandèmia, òbviament afavorida per la percepció de més seguretat associada a la mobilitat individual i a l’aire lliure. A Barcelona, per exemple, Roig-Costa et al. [-@Roig2021] apunten que gairebé un terç dels usuaris de micromobilitat van modificar el seu mode de transport habitual arran de la pandèmia, especialment els que abans es desplaçaven en transport públic o a peu.

El fet que els efectes de la pandèmia puguin ser permanents, i per tant no hi hagi una reversió total de la demanda de transport públic, tindrà conseqüències per a la sostenibilitat financera dels sistemes de mobilitat col·lectiva. Sobretot si s’hi afegeixen efectes permanents del teletreball. D’altra banda, una adopció més gran d’aquests modes de transport més respectuosos amb el medi ambient i amb la convivència a les grans ciutats també ofereix una via de millora de la sostenibilitat de la mobilitat i en la lluita contra els efectes nocius del trànsit excessiu i les externalitats negatives que se’n deriven. 

