# Teletreball, mobilitat i geografia dels mercats de treball i habitatge: canvis derivats de la pandèmia

###### Albert Gragera *(Universitat Autònoma de Barcelona)* {-}

## Introducció

El sever impacte de la COVID-19 i les mesures de distanciament social introduïdes per contrarestar-la han fomentat l’adopció del teletreball sense precedents. Això ha comportat una reducció de la mobilitat i reduccions importants dels nivells de contaminació en els moments més àlgids de la pandèmia, però també ha incrementat les desigualtats entre els treballadors amb menys ingressos i posicions no compatibles amb el teletreball (Mongey et al., [-@Mongey2021]; Reuschke i Felstead, [-@Reuschke2020]), que ha concentrat en els barris menys avantatjats els acomiadaments derivats dels confinaments, nivells més alts d’exposició a la infecció i les disrupcions en els serveis de transport públic.

Aquest capítol intenta fer una breu revisió de quines són les conseqüències esperables d’un increment important del teletreball per a la mobilitat i la geografia dels mercats de treball i habitatge. A aquest efecte revisem primer quins han estat els nivells de teletreball assolits durant la pandèmia i com de sostenibles semblen de cara al futur, quins són els efectes teòrics potencials que això pot tenir, quines evidències (tot i que preliminars) tenim sobre cap a on apunta l’evolució al llarg d’aquests anys de pandèmia i quines són les implicacions de cara a les polítiques públiques en la ciutat postcovid.

## El teletreball durant la pandèmia

Una anàlisi de les tasques realitzades en els diferents tipus d’ocupacions apunta que al voltant del $40\%$ - $50\%$ dels llocs de treball en països rics són potencialment compatibles amb el teletreball, xifra que baixa fins al voltant del $20\%$ - $30\%$ per a la resta d’economies desenvolupades, tot i que hi ha una heterogeneïtat elevada quant al sector industrial (Ozguzel, Veneri i Ahrend, [-@Ozguzel2020]). En general, el $80\%$ - $90\%$ dels llocs de treball amb formació i salaris alts són compatibles amb el teletreball, i només a l’entorn del $10\%$ ho són per als de menys formació.

Durant la pandèmia, als Estats Units el percentatge de teletreball es va situar al voltant del $20\%$ - $30\%$, mentre que a països com Espanya, França, Àustria i el Regne Unit va arribar fins a valors entre el $40\%$ - $50\%$, amb increments entre el $10\%$ - $30\%$ respecte dels nivells prepandèmia proporcionals al nivell de digitalització preexistent de cada economia (INE, [-@INE2020]; OECD, 2021a). Les dades més actuals mostren que aquest valors s’han reduït amb la nova normalitat, tot i que se situen encara força per sobre dels nivells prepandèmia. Per al cas d’Espanya, el percentatge de treballadors que teletreballen se situa de mitjana al voltant del $15\%$ (amb Madrid i Catalunya al capdavant, que assoleixen un $24\%$ i $18\%$, respectivament), i el model híbrid és el que s’imposa amb un $9,5\%$ dels treballadors que treballen la meitat dels dies o més i la resta ho fan només ocasionalment (EPdata, [-@Epdata2022]).

El principal dubte és si aquests nivells es mantindran després de la pandèmia, cosa que depèn dels efectes sobre la productivitat, les condicions de treball, els possibles efectes sobre les perspectives professionals dels treballadors i els beneficis que se’n derivin per a la conciliació de la vida laboral i familiar.

L’evidència disponible (via enquestes) sembla indicar que tant per part de les empreses com per part dels treballadors no hi ha hagut un descens de la percepció de la seva productivitat amb l’adopció del teletreball. De manera força consistent, entre un $75\%$ - $90\%$ de treballadors reporta el desig de seguir teletreballant en el futur, modalitat en què el principal benefici és l’estalvi de temps de desplaçament (Felstead i Reuschke, [-@Felstead2020]; Gascoigne, [-@Gascoigne2020]; IBM, [-@IBM2020]). Aquestes mateixes consultes entre els directius de les empreses exposen certs dubtes sobre les habilitats i els recursos del personal per dur a terme aquesta modalitat de treball de manera satisfactòria, però, tot i les despeses realitzades per adaptar-se al teletreball, sembla que la percepció ha estat generalment positiva, en la mesura que al voltant del $30\%$ - $50\%$ de les empreses es mostren disposades a mantenir-la (Australian Bureau of Statistics, [-@Ker2021]; Bartik et al., [-@Bartik2020]; Gascoigne, [-@Gascoigne2020]; Statistics Canada, [-@Statistics_Canada2020]). Especialment, el format híbrid és l’opció més esperable en opinió dels empresaris, que esperen que al voltant d’un $20\%$ de les hores treballades siguin fetes en format teletreball (Barrero et al., [-@Barrero2021]).

Un altre dels elements clau per a la sostenibilitat del teletreball a llarg termini depèn de la cultura empresarial imperant. La pandèmia ha introduït una disrupció important, però no és clar encara quins efectes pot tenir a mitjà o llarg termini en termes de retribució salarial (menys compensació per desplaçament), avaluació de rendiment i perspectives professionals, especialment en àmbits on la cultura empresarial es basa clarament en la presencialitat. Alguns estudis prepandèmia apunten que el teletreball a temps parcial no afecta les avaluacions del rendiment dels treballadors (Gajendran i Harrison, [-@Gajendran2007]; McCloskey i Igbaria, [-@Mccloskey2003]), en què les relacions amb els companys només es veuen deteriorades si es fa amb una freqüència més gran. I ja més recentment, el fenomen experimentat en diversos països denominat *the great resignation* (o *reshufle*) s’atribueix (en part) al pes més gran que ara donen els treballadors a la flexibilitat laboral, de manera que deixen de banda companyies amb cultures empresarials més antiquades que han fet obligatòria la tornada a la presencialitat^[El terme *great resignation* (encunyat per Anthony Klotz) descriu el gran increment de renúncies voluntàries durant la segona fase de la pandèmia, justificades també per l’acumulació de renúncies naturals que es van aturar per la incertesa inicial. Tot i això, altres autors ho denominen *“reshufle”* que dona més la idea de canvi de lloc de treball que no pas “resignation” que només s’associa a deixar la feina (i es pot interpretar com una sortida del mercat de treball).].  No obstant això, també podem apuntar alguns inconvenients tant per a empreses com per a treballadors. Segons enquestes fetes a Dinamarca (on l’experiència amb el teletreball és força més àmplia), directius i càrrecs intermedis reporten que experimenten una dificultat més gran a l’hora de gestionar els equips a distància, cosa que podria implicar un descens de la productivitat a llarg termini^[El resum d’aquesta enquesta es pot veure al següent [enllaç](https://www.lederne.dk/presse-og-nyheder/analyser-og-undersoegelser/ledere-og-ledelse/flertal-af-ledere-vil-gerne-tilbage-paa-kontoret#:~:text=I%20unders%C3%B8gelsen%20svarer%2067%20procent,lederne%20har%20ingen%20umiddelbare%20pr%C3%A6ferencer.)].  Així mateix, en termes de conciliació dels treballadors, també cal destacar que hi ha certa evidència que aquesta flexibilitat pot induir a incrementar el total d’hores treballades i la freqüència del treball als vespres i caps de setmana (Eurofund i ILO, [-@Eurofound2017]), tot i que sigui a canvi de més autonomia i capacitat per gestionar el temps de treball i combinar-lo a conveniència amb tasques de cura dels infants a càrrec, per exemple.

## Els potencials efectes del teletreball a mitjà o llarg termini

El teletreball obre la porta a canvis potencials en la localització d’activitats i residència, en modificar la geografia del mercat de treball i el d’habitatge. Això queda patent si ens plantegem quina és la lògica de decisió de localització per part d’empreses o residents, comparant avantatges i inconvenients d’emplaçaments en àmbits de centralitat, per exemple.

Per una banda, les empreses que es localitzen a prop d’altres agents econòmics poden disposar d’un avantatge competitiu degut a les economies d’aglomeració, amb nivells més alts de productivitat derivats de: *i)* una difusió més ràpida d’idees i innovacions; *ii)* accés a una oferta més gran de treballadors especialitzats amb perfils escaients per a les necessitats de l’empresa, i *iii)* més varietat en els inputs per subministradors més propers i amb un cost més baix per l’elevada competència. A més, si les empreses es localitzen a prop d’on resideixen els seus treballadors, hi pot haver un estalvi en salaris perquè sigui menys necessari compensar-ne els costos de desplaçament. Per altra banda, aquests avantatges derivats de l’aglomeració es veuran parcialment compensats pels efectes negatius derivats d’uns preus dels terrenys o espais d’oficina més alts en els àmbits de més centralitat i amb més demanda, alhora que també s’experimenten costos de transport més alts deguts a la congestió. Així, en la decisió de localització les empreses contraposen els efectes positius d’aglomeració amb els negatius, en què els costos de transport actuen com a força d’arbitratge entre ambdós. En concret, el teletreball aporta a les empreses l’oportunitat de reduir la compensació salarial i obre la porta a un mercat de treball més ampli (no restringit a l’entorn de l’àrea funcional urbana), així com a estalvis en els costos dels espais d’oficina, que es poden reduir amb menys presencialitat del personal. Així doncs, sumat a l’efecte de les economies d’aglomeració, això sembla indicar una relativa i esperable intensificació de l’atractiu d’àmbits d’alta centralitat per a les empreses.

En aquesta mateixa línia, les llars decideixen el seu lloc de residència segons les seves necessitats d’habitatge (dimensió i altres característiques), el consum d’altres béns i els costos de desplaçament (principalment el laboral), condicionat per la seva restricció pressupostària. Així, en àmbits d’alta centralitat se sol donar una oferta d’habitatges de dimensions més reduïdes a uns preus més elevats, degut a l’elevada demanda, mentre que localitzacions més distants ofereixen habitatges més grans a un preu inferior per metre quadrat. Les llars també experimenten efectes positius de l’aglomeració, com ara un accés més gran a un ventall més ampli d’oportunitats de feina (on es concentren empreses) i en el consum de béns i serveis que ofereix la ciutat (*amenities*); i també efectes negatius, per exemple, la congestió i contaminació en termes de soroll o pitjor qualitat de l’aire^[Durant la pandèmia un altre efecte negatiu ha estat una percepció més gran de risc de contagi en àmbits urbans densos, on les restriccions per garantir el distanciament social han estat més palpables.].  D’aquesta manera, l’accés a més espai d’habitatge a un preu inferior empeny les llars cap a localitzacions més distants (igual que els efectes negatius de l’aglomeració), mentre que el cost del transport i el desig de consumir *amenities* urbanes els empeny cap a emplaçaments més centrals. Així, el teletreball obre la porta a les llars a relocalitzar-se i poder accedir a habitatges de dimensions més grans que estan més distants, la qual cosa fa estalviar costos de desplaçament (ara menys freqüents), degut a la major renda disponible si els salaris no s’adapten a la nova situació.

L’equilibri entre aquestes forces és el que dona forma a les ciutats, i configura la localització dels diferents agents econòmics i grups socials, amb implicacions per als preus dels habitatges, patrons de mobilitat i també en termes de desigualtat. Els desequilibris entre aquestes forces han donat lloc a processos dinàmics que han portat a la suburbanització, esperonada per costos de transport baixos i infraestructura orientada a l’automòbil, especialment per als grups socials de renda més alta. Posteriorment, el guany d’importància dels serveis i l’orientació cap a la innovació ha donat molta més rellevància a les economies d’aglomeració (també en el consum), que han esperonat un procés de *gentrificació* dels àmbits de més centralitat. Així, les formes urbanes complexes que observem són pedaços derivats de les decisions de localització sobretot dels grups de renda més alta, que poden expulsar de les zones més desitjades a partir de la pressió dels preus de l’habitatge (Florida & Adler, [-@Florida2018]).

Trobem evidències sobre com els canvis en els nivells d’accessibilitat han afectat aquests processos al nostre entorn més proper a Garcia-López [-@Garcia2012] i Garcia-López et al. [-@Garcia2015], que analitzen els efectes de la provisió d’autopistes i ferrocarril a Barcelona. Ara, alts nivells d’adopció del teletreball (especialment si són sostinguts en el temps) poden fer decantar de manera similar l’equilibri entre aquestes forces, i modificar les decisions dels diferents agents i la geografia resultant dels mercats de treball i habitatge, a més dels patrons de mobilitat i externalitats del transport que se’n deriven. És per això que resulta important analitzar les evidències empíriques preliminars que ens ajudin a determinar quines poden ser les conseqüències per a les nostres ciutats de nivells elevats de teletreball postpandèmia.

## Evidències disponibles

### Evidències de la relació entre teletreball, mobilitat i localització

En termes de mobilitat, el factor més preocupant del teletreball a llarg termini és saber si el potencial efecte relocalització (i l’increment de distància de desplaçament associat) pot sobrepassar el suposat efecte substitució (nombre de desplaçaments eliminats).

En les primeres fases de la pandèmia, l’opinió imperant semblava centrar-se majoritàriament en aquest efecte substitució entre el nombre de desplaçaments i el teletreball, i es veia com una de les eines de gestió de la demanda de transport més adients per reduir l’ús del vehicle privat. No obstant això, l’evidència prepandèmia ja apuntava que aquest efecte substitució només s’assolia a curt termini, mentre que estudis que analitzen períodes i mostres més amplis apunten més aviat a una certa complementarietat (Mokhtarian, [-@Mokhtarian2002]). Aquells que teletreballen tenen tendència a fer desplaçaments més llargs o de més duració (però menys freqüents) fins al seu centre de treball, mostren també un increment del nombre, la freqüència i la distància d’altres desplaçaments, i ho fan amb modes menys sostenibles ja que tendeixen a localitzar-se en zones llunyanes amb menys serveis de transport públic (Mokhtarian et al., 2004 [-@Mokhtarian2004]; Zhu, [-@Zhu2012]; Kim, [-@Kim2017]; De Abreu e Silva i Melo, [-@De2018]).

Una *suburbanització* més gran de les ciutats com a conseqüència d’una expansió del teletreball ha estat suggerida per diversos autors com a conseqüència probable de la pandèmia (Florida et al., [-@Florida2020]; Overman i Nathan, [-@Nathan2020]; Denham, [-@Denham2021]). Diversos models teòrics apunten aquesta mateixa línia (Delventhal et al., [-@Delventhal2022]; Brueckner et al., [-@Brueckner2021]; Lennox, [-@Lennox2020]). El teletreball motiva la relocalització de residència dels àmbits de més centralitat cap als suburbis, la qual cosa redueix la pressió sobre el mercat d’habitatge en àmbits centrals (baixada de preus) i l’augmenta a la perifèria (increment de preus). És a dir, el gradient de preus entre centre i perifèria s’aplana pels canvis en la demanda relativa entre aquests àmbits. A més, Brueckner et al. [-@Brueckner2021] mostren que això es dona quan les ciutats difereixen en nivells de productivitat, però quan només difereixen en el nivell d’*amenities* aquestes diferències són més elevades allà on es muden els teletreballadors i, per tant, incrementen la demanda d’habitatge.

Per tant, sempre que l’efecte relocalització tingui més pes que l’efecte substitució, el teletreball comportaria un augment net de la distància recorreguda i les emissions associades. Això és especialment clar en el model híbrid de teletreball, en el qual, tot i que la relocalització pot estar més acotada a l’entorn metropolità proper per la impossibilitat de desconnexió total de la ubicació del centre de treball, l’efecte substitució és inferior i implica la necessitat de seguir fent un cert nombre de desplaçaments laborals.

En contraposició a la tendència de suburbanització de la demanda d’habitatge, alguns d’aquests mateixos models també mostren com el teletreball és esperable que empenyi els centres de treball a localitzar-se en àmbits de més centralitat. Això es deu a l’efecte combinat de les economies d’aglomeració (sempre que tinguin un pes important sobre la productivitat de l’empresa) i l’estalvi en les despeses d’espais gràcies al nombre més baix de treballadors que requereixen presencialitat (Delventhal et al., [-@Delventhal2022]; Lennox, [-@Lennox2020]). A més, un altre avantatge del teletreball per a les empreses és l’expansió del seu mercat potencial de capital humà, que incrementa la competència, així com una reducció intrínseca de la necessitat de compensació salarial pel desplaçament laboral; ambdós factors apunten una reducció potencial dels costos laborals^[Cal fer notar que, en aquesta afirmació, estem negligint les rigideses associades a un procés de transició degut a contractes vigents i al potencial poder de negociació de les associacions sindicals.].  Un avantatge, a més, que fa relativament més favorable una localització en àmbits d’alta centralitat, on recordem que les economies d’aglomeració augmenten la productivitat^[Evidències recents apunten la relació negativa entre distància de desplaçament i productivitat, amb una reducció del $5\%$ de les patents per inventor per cada 10 km d’increment de la distància entre residència i lloc de treball (Xiao et al., [-@Xiao2021]).].  Evidentment, les característiques heterogènies de les empreses farà que els incentius per adoptar el teletreball (i també en termes de relocalització) siguin substancialment diferents. Per exemple, és esperable que les empreses que facin front a uns costos immobiliaris més elevats i tinguin un factor treball més car, siguin les que tinguin uns incentius més elevats.

Combinant aquestes tendències de suburbanització de la residència i de centralització dels llocs de treball, és esperable que comportin un increment de la distància recorreguda de desplaçament laboral encara major i un transvasament modal cap al vehicle privat (generalment més competitiu en distàncies llargues i en àmbits menys densos). Si això genera uns nivells de congestió suficientment alts pot arribar a contrarestar fins a cert punt els incentius de localització, però cal tenir en compte que ho faria a expenses de generar un cost social més alt en termes d’externalitats.

### Evidències dels canvis de geografia del mercat d’habitatge

Les dades semblen corroborar en línies generals aquests resultats teòrics. Tot i que encara són incipients i cal prendre-se-les amb cautela, sembla que el teletreball ha portat canvis de preferències en el mercat immobiliari amb una major demanda d’habitatges més grans, amb espais exteriors i de nova construcció. Cal destacar que aquestes característiques en entorns urbans d’alta centralitat tenen preus particularment elevats i, per tant, són demandes més senzilles de satisfer en àmbits més distants, tal com apunta el canvi de preferències cap a l’extraradi de grans ciutats i ciutats secundàries al llarg de 2020, segons BDE [-@Alves2021].

Als Estats Units, Liu i Su [-@Liu2021] mostren que la demanda d’habitatge a partir de la pandèmia s’ha reduït als barris amb alta densitat de població, degut principalment a una menor necessitat de residir a prop dels centres de treball i a un valor inferior del consum d’*amenities*. Aquells barris on els preus prepandèmia eren més alts són els que han vist una reducció de la demanda més acusada, que ha virat cap a emplaçaments suburbans^[Aquest treball analitza la situació del mercat immobiliari als Estats Units per al període del gener de 2020 a l’abril de 2021.].  Brueckner et al. [-@Brueckner2021] mostren que tant els preus de venda com de lloguer són més baixos en àmbits amb una elevada oferta de llocs de treball compatibles amb el teletreball i alta productivitat quan es comparen amb el període prepandèmia (tant amb dades anuals com mensuals), així com un aplanament del gradient de preus d’habitatge entre centre i perifèria en les àrees metropolitanes on això passa.

S’obtenen evidències en aquesta mateixa línia al Regne Unit, on després del confinament les cerques d’informació a portals digitals immobiliaris s’incrementa entre un $60\%$ - $80\%$ per a habitatges de compra respecte del 2019, mentre que les consultes d’habitatge de lloguer ho fan al voltant del $20\%$ - $40\%$. Aquesta diferència inicial experimentada durant el 2020 es redueix a poc a poc i a finals de 2021 les cerques s’estabilitzen per a ambdós tipus d’habitatge al voltant del $50\%$ d’increment respecte de 2019 (Rightmove, [-@Rightmove2021]). Aquesta mateixa font assenyala que l’origen de les consultes apunta que la proporció de cerques que busquen deixar les principals ciutats han augmentat entre un $10\%$ - $15\%$ (tant per a compra com per a lloguer). En concret, comparant la proporció de cerques de gent que resideix fora de Londres i vol mudar-s’hi amb aquelles que hi resideixen i la volen deixar, es pot veure que la marcada tendència a una major entrada ($60\%$) que sortida ($40\%$) s’ha invertit a partir de la pandèmia ($45\%$ - $55\%$, respectivament)^[Aquesta inversió en els fluxos d’entrada i sortida no es dona a altres ciutats del Regne Unit, cosa que apunta que les dinàmiques locals del mercat d’habitatge són complexes.].  La destinació d’aquestes consultes al llarg de 2020 i 2021 mostra que els residents a Londres principalment busquen habitatges de propietat a l’entorn metropolità més proper i ciutats secundàries ben connectades i un alt nivell d’*amenities*. De manera interessant, les dades de Rightmove també mostren la relació entre demanda d’habitatge i transport públic. Agafant com a exemple les estacions de la Northern Line es pot veure com la demanda d’habitatges de compra al llarg de la línia ha disminuït fins a un $60\%$ a l’entorn de les estacions més cèntriques i ha augmentat entre un $20\%$ - $100\%$ amb una tendència creixent a mesura que ens movem cap als extrems^[Aquest efecte d’increment als extrems és més marcat el 2020 i s’atenua relativament el 2021, però, en canvi, esdevé més marcada la reducció en les estacions més cèntriques.]. 

No obstant això, cal destacar que els costos de transport no són el factor més important en la decisió de localització, en la qual, per exemple, el cost de l’habitatge té un pes més important. Així, males perspectives en el mercat hipotecari poden compensar un incentiu més gran de relocalització pel teletreball. Els residents amb habitatge en propietat poden veure’s fixats a la seva residència actual (amb hipoteques de tipus baixos) ja sigui pel cost financer més elevat que tindria entrar en un mercat en una dinàmica d’escalada dels tipus d’interès, com per l’aversió a vendre amb preus a la baixa. En aquest sentit, evidències prepandèmia mostren que per cada 1.000 \$ d’increment real del cost hipotecari els canvis d’habitatge es redueixen de l’ordre del $12\%$ (Ferreira et al., [-@Ferreira2010]).

### Evidències dels canvis de geografia del treball

Si ens centrem en l’evidència provinent del mercat de treball, podem veure que, a més d’una adopció del teletreball molt més àmplia en llocs de treball d’alta formació, aquesta modalitat també sembla haver estat més elevada en organitzacions de dimensions més grans i emplaçades en àmbits d’alta centralitat (Shearmur et al., 2021 [-@Shearmur2022]). Els treballadors en àmbits d’alta centralitat són els que reporten una voluntat més gran de reduir la presencialitat: un $45\%$ espera poder fer més teletreball, especialment entre els de més qualificació. En aquesta mateixa línia, Muro i You [-@Muro2022] mostren amb dades dels Estats Units que les indústries tecnològiques (on el teletreball ha tingut una adopció més gran) han vist un descens del nombre de llocs de treball a les grans metròpolis i un increment a ciutats mitjanes, especialment en emplaçaments amb una altra qualitat de vida, cosa que apunta cap a una tendència a certa descentralització d’aquest tipus de llocs de treball.

L’evidència sobre els preus del sector immobiliari mostren un descens acusat per a tots els segments amb l’arribada de la pandèmia. No obstant això, els que pateixen reduccions més fortes són hotels i locals comercials, seguits de prop pel segment d’oficines. Al llarg de la pandèmia els preus per a aquests segments han remuntat, però al maig de 2021 encara es trobaven entre un $20\%$ - $30\%$ per sota dels nivells prepandèmia (Hoesli i Malle, [-@Hoesli2021]). Tanmateix, tant els segments residencials com industrials es van recuperar amb més rapidesa i ja es van situar a nivells prepandèmia al juliol de 2020, i fins i tot els locals industrials han incrementat preus per la major demanda d’activitats logístiques (comerç electrònic).

Si ens centrem en el segment de les oficines, alguns autors suggereixen que les tendències prepandèmia cap a la «coworkització» dels espais de treball, amb més espais d’interrelació i menys taules de treball, s’ha accelerat en fer-se palès que moltes tasques individuals poden fer-se sense problemes des de casa. Tot i que això ha comportat una certa reducció de la densitat de llocs de treball (al voltant del $10\%$), el teletreball encara implica una important reducció neta de la demanda d’espai d’oficines, i aporta un potencial estalvi en els àmbits on els preus són més elevats (Carson et al., [-@Carson2020]). Bergeaud et al. [-@Bergeaud2021] mostren com, a França, els preus de les oficines ubicades en regions amb alts nivells de teletreball han estat revisats a la baixa amb més freqüència. En particular, l’increment d’una desviació estàndard del teletreball es relaciona amb una reducció del preu del $7\%$, amb un fort component geogràfic. En tot cas, val la pena destacar que les previsions d’entitats bancàries mostren que esperen un increment sostingut dels preus de lloguer dels espais d’oficines en els àmbits de més centralitat (*prime*) i una davallada a la resta de localitzacions, i això reforça la visió d’efectes diferenciats en la geografia del treball pel que fa a oficines (Hoesli i Malle, [-@Hoesli2021]).

En qualsevol cas, aquestes dinàmiques s’afegeixen a les de suburbanització de la residència, cosa que implica un desequilibri en l’oferta i la demanda en algunes zones, que es reforcen mútuament. En la línia del que s’ha exposat en els models teòrics analitzats abans, el desequilibri de la demanda d’habitatge cap als suburbis pot reforçar l’incentiu del moviment d’empreses cap als àmbits de més centralitat degut a la reducció dels preus, amb un major cost-eficiència per l’espai estalviat per la presencialitat més baixa.

Es preveu que aquests canvis puguin tenir derivades en la distribució de l’activitat econòmica afectada per l’adopció del teletreball, amb menor consum de serveis personals, hostaleria i altres en els entorns on les empreses adopten el teletreball. Barrero et al. [-@Barrero2021] apunten a una reducció esperada entre un $5\%$ - $10\%$ respecte dels nivells prepandèmia en els àmbits de més centralitat i un increment en localitzacions més distants. Això té implicacions en el mercat de treball, en tant que els llocs compatibles amb el teletreball són «mòbils», però aquests tipus de llocs presencials no. Per tant, la reducció de la demanda en entorns centrals implicarà un ajust en termes de llocs de treball o salaris (Autor i Reynolds, [-@Autor2020]; Althoff et al., [-@Althoff2022]).

Així, sembla clar que els beneficis del teletreball queden capturats pels treballadors amb alt nivell educatiu i rendes altes, mentre que els segments menys afavorits carreguen amb les conseqüències negatives, la qual cosa incrementa els efectes de la bretxa digital. Aquesta relocalització en direccions oposades té implicacions negatives per a la mobilitat, especialment per a un segment de població que depèn del transport públic i on els canvis semblen apuntar en la línia d’empitjorar la seva accessibilitat al mercat de treball. Això es pot traduir en un augment de l’ús del vehicle privat (especialment entre els que tenen possibilitats econòmiques), ja que les reduccions d’accessibilitat s’associen amb increments dels nivells de motorització (Matas et al., [-@Matas2009]).

## Conclusions

El que s’ha descrit en els apartats anteriors apunta que el teletreball es mantindrà en quotes més elevades que en la situació prepandèmia, i que això implica modificar la relació de forces que conformen les nostres ciutats, cosa que afecta la geografia del mercat d’habitatge, treball i mobilitat. La tendència a la suburbanització de la residència (per a certs segments de població) i a la centralització dels llocs de treball sembla el resultat més plausible, però té implicacions importants de cara a les polítiques de mobilitat.

Aquesta tendència resulta especialment preocupant per al transport públic, ja que en llocs més distants dels àmbits de més centralitat presenta una oferta de serveis molt més limitada i pot afavorir una mobilitat més dependent del vehicle privat. El teletreball també comporta una major flexibilització dels patrons de mobilitat, àmbit en què topa amb certa rigidesa del transport públic, on els serveis de mobilitat col·laborativa poden ser un bon complement per tal que no perdi competitivitat enfront del vehicle privat. A més, el teletreball pot tenir un impacte sobre els ingressos dels operadors de transport públic si els usuaris passen a títols ocasionals per compensar la incertesa en el nombre de desplaçaments mensuals que han de fer, cosa que se suma a uns dèficits acumulats durant la pandèmia força importants. Així mateix, la relocalització associada al teletreball pot tenir un impacte sobre el finançament dels serveis públics per la banda de la reducció de la recaptació d’impostos, i això pot arribar a imposar la retallada de serveis (en concret de transport públic, el finançament del qual ja pateix força).

En aquest marc, el teletreball pot ser un nou al·licient per a un augment de l’ús del vehicle privat. Per començar perquè la flexibilització laboral dona més opcions per evitar els períodes de congestió, i ofereix temps de viatge més competitius. A més, fer desplaçaments amb menys freqüència pot imposar un cost més baix sobre l’usuari. Això es pot compensar en part amb l’efecte relocalització (més distància), però aquest efecte també empeny els usuaris a àmbits amb alternatives menys competitives en termes de transport públic. Tot això, augmenta la conveniència en l’ús del vehicle privat, en un marc amb un conjunt d’incentius que li són del tot favorables. Això, porta a pensar que caldrà redoblar esforços en termes de gestió de la demanda per compensar el major atractiu de la mobilitat privada.

Saber si el canvi més important es donarà en la geografia del mercat d’habitatge o de treball és encara impossible amb les dades disponibles. El que sí que sabem és que el mercat d’habitatge (com a bé durable) té certes rigideses i per valorar-ne canvis substancials cal que els incentius estiguin alineats en certa direcció durant força temps. És esperable que els municipis metropolitans amb alts nivells d’*amenities* i qualitat de vida siguin els que experimentin el gruix de la pressió de relocalització. Aspectes com ara les perspectives econòmiques i d’inflació de ben segur que tindran un paper en l’avenç o estancament dels patrons que sembla que comencen a emergir.

Tot això posa de manifest la necessitat de vincular de manera molt més estreta les polítiques de planificació urbana, habitatge, treball i transport. En concret, la rellevància en termes de mobilitat fa que sigui desitjable monitorar de prop l’evolució dels mercats d’habitatge i treball (juntament amb els patrons de mobilitat), per tal de detectar de manera primerenca aquestes possibles noves tendències i intervenir per corregir-ne les conseqüències negatives.
