# Mobilitat i desigualtat: Impactes distributius dels efectes de la pandèmia en la mobilitat

###### Paula Bel *(Universitat Abat Oliva)* {-}

## Introducció 

El 30 de gener de 2020 l’Organització Mundial de la Salut (OMS) publicava les primeres dades oficials de morts per la COVID-19 i es confirmaven els primers 7.818 casos, principalment localitzats a la Xina (WHO, [-@Who2020]). En poc temps, el virus es va anar expandint i transportant a altres països i continents i poques setmanes després, l’11 de març de 2020, l’OMS determinava la COVID-19 com una pandèmia mundial (WHO, 2020b [-@Whob2020]). L’expansió global del virus i la velocitat a la qual es propagava va fer reaccionar governs i autoritats sanitàries de tot el món. Per tal de reduir la propagació de la COVID-19, els governs van aplicar mesures de confinament i distanciament social, les quals van alterar la vida diària de la població i la participació presencial en les activitats (De Vos, [-@De2020]; Mouratidis i Papagiannakis, [-@Mouratidis2021]). Molts  països van clausurar els centres educatius i van tancar fronteres, també es van cancel·lar els esdeveniments públics i es van prohibir les activitats socials. Els desplaçaments únicament estaven autoritzats per als treballadors de serveis essencials o per causes degudament justificades. En algunes ciutats també es van aplicar mesures en el transport públic, com ara la prohibició de la venda directa de bitllets per part dels conductors o la limitació de la capacitat de passatgers (Lozzi et al., [-@Lozzi2020]). 

Les mesures aplicades per tal de contenir el virus ràpidament van tenir un impacte sobre les taxes de mobilitat que van  afectar tant en el transport públic com en el privat. D’acord amb les dades de mobilitat proporcionades per OurWorldInData, dos mesos després que l’OMS hagués determinat la COVID-19 com una pandèmia mundial, la reducció del nombre de desplaçaments en transport públic a l’Àsia va arribar a assolir xifres a l’entorn del $75\%$ (Filipines, $76\%$), a Oceania i Europa del $70\%$ (Nova Zelanda, $69\%$, i França, $70\%$) i a Sud-amèrica, Àfrica i Nord-amèrica del $60\%$ (Colòmbia, $64\%$, Sud-àfrica, $62\%$, i el Canadà, $60\%$). El transport privat també va patir una forta davallada; no obstant això, no va ser tan acusada com la del transport públic. En les mateixes dates, d’acord amb les dades de mobilitat proporcionades per Apple, la reducció del transport privat per a les Filipines va ser del $70\%$ i per a Sud-àfrica i Colòmbia del $50\%$. En el cas de França i del Canadà, la mobilitat es va reduir un $30\%$ i un $20\%$, respectivament, i a Nova Zelanda un $5\%$. La reducció de la mobilitat també va impactar de manera diferent segons el nivell de renda dels països. D’acord amb Medimorec et al. [-@Medimorec2020], els països d’ingressos alts van registrar descensos de mobilitat molt més elevats que els països d’ingressos mitjans i baixos. La resposta de la mobilitat a les ordres de confinament i distanciament social dictades per les autoritats també va variar entre països (Praharaj et al., [-@Praharaj2020]).

Tot i que són diversos els factors que explicarien la reducció de la mobilitat durant la pandèmia, dos dels principals determinants  són el teletreball i la percepció de l’elevat risc que tenen els usuaris del transport públic a contreure-hi el virus. El treball de Przybylowski [-@Przybylowski2021] analitza l’impacte de la pandèmia en el comportament dels usuaris del transport públic a Gdansk (Polònia). Un dels principals resultats de l’estudi mostra que el $91\%$ dels enquestats van declarar un descens o una renúncia total a utilitzar el transport públic durant la pandèmia, i n’assenyalaven com a principals motius el fet d’haver passat a la modalitat de teletreball i la por a contreure la infecció. Barbieri et al. [-@Barbieri2021] avaluen la percepció del risc a contreure el virus en el sector del transport en deu països diferents: Austràlia, el Brasil, la Xina, Ghana, l’Índia, l’Iran, Itàlia, Noruega, Sud-àfrica i els Estats Units. Els principals resultats que troben els autors mostren que la probabilitat que perceben els individus de contreure el virus en el transport s’incrementa quan es passa de viatjar en transport privat a viatjar en transport públic. Segons els resultats de l’estudi, els dosmitjans de transport més segurs per desplaçar-se són l’automòbil utilitzat de manera individual i la motocicleta. En canvi, els dos modes de desplaçament més perillosos són l’avió i l’autobús. Rahimi et al. [-@Rahimi2021] investiguen la percepció del risc a contreure el virus en el transport públic i els cotxes compartits en l’àrea metropolitana de Chicago. Els principals resultats de l’estudi mostren que la percepció del risc a contreure el virus pot variar en funció de les característiques socioeconòmiques i de salut del lloc on resideixen els individus; tanmateix, aquells individus que utilitzaven el transport públic amb regularitat abans de la pandèmia perceben menys risc d’utilitzar el transport públic durant la pandèmia.

El teletreball també ha sigut un dels altres grans factors que han impactat sobre la reducció de la mobilitat durant la pandèmia. A mesura que la pandèmia anava avançant i el distanciament social era necessari per reduir els contagis, molts  governs arreu del món van encoratjar o obligar a minimitzar la presència física a la feina (OECD, [-@Organisation2021]). Tot i que el teletreball ha estat una mesura utilitzada per reduir la probabilitat de contraure i propagar el virus, no totes les feines han pogut adaptar-se a aquesta modalitat. El treball de Stantcheva [-@Stantcheva2022] fa una anàlisi de la literatura sobre l’impacte que ha tingut la COVID-19 en la desigualtat analitzada des de diferents perspectives, entre les quals destaca l’impacte de la pandèmia en el teletreball. Els resultats de l’estudi mostren que la capacitat de teletreballar es distribueix de manera desigual segons el nivell d’ingressos, i que els ocupats d’ingressos baixos són els que tenen menys oportunitats per poder teletreballar. A més a més, mentre que els empleats d’ingressos més alts poden obtenir una prima salarial treballant des de casa, aquests guanys addicionals de productivitat per als ocupats d’ingressos més baixos estan molt més limitats. 

La reducció de la mobilitat durant la pandèmia ha estat generalitzada arreu del món i, tot i que ha contribuït a millorar els nivells d’alguns dels paràmetres que determinen la contaminació ambiental (Muhammad et al., [-@Muhammad2020] Yang et al., [-@Yang2021]), també ha generat una nova font de desigualtats. La pandèmia ha posat en evidència que la capacitat de reduir la mobilitat durant aquest temps s’ha distribuït de manera desigual segons el nivell de renda de la població. Els treballs que han analitzat els impactes distributius dels efectes de la pandèmia en la mobilitat indiquen que els individus amb un nivell d’ingressos més alt presenten taxes de reducció de la mobilitat superiors als individus amb menys ingressos. Aquest treball fa una revisió de la literatura sobre els estudis de mobilitat en temps de pandèmia abordats des de la vessant de la desigualtat. És important esmentar que la gran majoria d’aquests estudis s’han portat a terme mitjançant l’explotació de dades que alliberen els sistemes de posicionament de telefonia mòbil i que l’interès acadèmic més gran s’ha generat als Estats Units. El treball s’estructura de la manera següent. En un primer apartat es presenten els principals resultats dels estudis que han analitzat els impactes distributius dels efectes de la pandèmia en la mobilitat en l’àmbit nacional. Posteriorment, en un segon apartat, es du a terme la revisió dels principals articles que han focalitzat l’anàlisi en l’àmbit urbà. El treball finalitza amb unes conclusions i reflexions finals. 

## Impactes distributius dels efectes de la pandèmia en la mobilitat en l’àmbit nacional

Per a **Espanya**, en primer lloc, trobem el treball d’Hernando et al. [-@Hernando2020], que analitza els efectes de la pandèmia en la mobilitat desagregats per nivell d’ingressos en quatre períodes de temps diferents: el període preconfinament (de l’1 de gener de 2020 al 15 de març de 2020), el període de confinament (del 15 de març de 2020 al 20 de juny de 2020), el període de vacances d’estiu (del 20 de juny de 2020 al 14 de setembre de 2020) i el període de nova normalitat (del 14 de setembre de 2020 al 18 d’octubre de 2020). Els autors han aproximat la variable de mobilitat a través del còmput del radi de gir, el qual mesura la distància recorreguda per un mateix dispositiu de telefonia mòbil durant un dia. La metodologia d’investigació emprada en l’estudi ha estat l’anàlisi descriptiva de dades. Els resultats que troben els autors mostren que durant el període de preconfinament la mitjana del radi de gir és més elevada per a les poblacions amb ingressos baixos (8,1 km) que per a les poblacions amb ingressos alts (6,9 km). En el període de confinament, la mitjana del radi de gir per a les poblacions amb ingressos alts se situa al voltant dels 0,9 km i per a les poblacions amb ingressos baixos és de 3,3 km. És a dir, en termes relatius les poblacions amb ingressos alts veuen reduïda la seva mobilitat un $266\%$ en comparació amb les poblacions més pobres. Durant el període de vacances d’estiu, la meitat de la població amb salaris més alts experimenta un increment de la mobilitat un $70\%$ superior respecte als valors del període preconfinament. En aquest mateix període, la mobilitat de les poblacions amb els salaris més baixos torna als nivells de prepandèmia. En últim lloc, en el període de nova normalitat, la mitjana del radi de gir per a les poblacions amb ingressos baixos és de 6,9 km i per a les poblacions amb ingressos alts és de 4,7 km. 

Per als **Estats Units**, també trobem el treball de Yilmazkuday [-@Yilmazkuday2020]. El treball de Yilmazkuday [-@Yilmazkuday2020] analitza si les mesures de distanciament social han impactat de manera diferent entre individus segons el nivell d’ingressos, el nivell d’estudis i la raça/ètnia del grup al qual es pertany. Les dades de mobilitat analitzades en l’estudi comprenen el període temporal que va del 21 de gener de 2020 al 26 de juny de 2020. A diferència del treball d’Hernando et al. [-@Hernando2020], el treball de Yilmazkuday [-@Yilmazkuday2020] captura la variable mobilitat a través d’un índex d’exposició, el qual mesura el nombre de dispositius diferents de telefonia mòbil que visiten el mateix comerç durant el mateix dia. La metodologia d’anàlisi emprada en l’estudi està basada en un model de diferències en diferències. Els principals resultats de l’estudi mostren que, després de la declaració d’emergència sanitària proclamada a mitjans de març de 2020, els col·lectius que han experimentat un distanciament social més gran han estat els col·lectius situats en el quartil superior d’ingressos, amb el nivell més alt d’estudis o que són asiàtics. Sobre el nivell d’ingressos de la població, el treball mostra que els col·lectius que són en el $25\%$ de renda superior redueixen la mobilitat un $31\%$ més que el $25\%$ dels individus amb menys ingressos, un $32\%$ més que els individus posicionats en el segon quartil de renda i un $25\%$ més que els individus que pertanyen al tercer quartil de renda.

Continuant amb els Estats Units, però en l’**àmbit estatal**, el treball de Matson et al. [-@Matson2021] analitza els efectes de la pandèmia en la mobilitat segons el nivell d’ingressos per al cas de **Califòrnia**. Per portar a terme l’estudi, els autors han comparat una base de dades de mobilitat elaborada a partir d’enquestes dutes a terme abans de la pandèmia (2019) amb una base de dades de mobilitat elaborada a partir d’enquestes fetes durant la pandèmia (març i abril del 2020). Les variables de mobilitat utilitzades s’han aproximat a través de qüestionaris que responen a preguntes del tipus: nombre de dies a la setmana que es treballa presencialment, nombre de dies a la setmana que es teletreballa, freqüència amb la qual es fan compres electròniques, nombre de vegades mensuals o setmanals que es passeja o s’utilitza la bicicleta com a activitat de lleure i nombre de vegades que s’ha llogat un vehicle amb conductor en els últims trenta dies. La metodologia d’anàlisi està basada en l’anàlisi exploratòria de dades. Els principals resultats que troben els autors mostren que no hi ha diferències significatives, entre les dades d’abans de la pandèmia i les dades de durant la pandèmia, per nivell d’ingressos sobre la freqüència amb la qual es fan compres electròniques i el nombre de vegades mensuals o setmanals en què es passeja o es fa servir la bicicleta com a activitat de lleure. En canvi, les diferències per nivells de renda sí que són significatives per al nombre de dies a la setmana que es treballa presencialment. Amb pandèmia, els individus de rendes més altes són els que deixen d’acudir presencialment al lloc de treball amb una proporció més gran. Referent al nombre de dies a la setmana que es teletreballa, els autors també mostren que amb pandèmia els individus d’ingressos més alts són els que, proporcionalment. teletreballen més (cinc dies a la setmana o més de cinc). Referent al nombre de vegades que s’ha llogat un vehicle amb conductor en els últims trenta dies, els autors mostren que abans de la pandèmia els individus d’ingressos alts eren els que, proporcionalment, més feien servir el servei; en canvi, amb pandèmia, són els individus de rendes més baixes els que més l’utilitzen. 

En l’**àmbit regional** i per al cas dels **Estats Units**, en primer lloc, trobem el treball de Weill et al. [-@Weill2020], que analitza l’impacte de la declaració d’emergència en la mobilitat a través del percentatge de dispositius mòbils que es queden completament a casa, les diferents ubicacions visitades diàriament pels dispositius, la distància mitjana recorreguda fora de casa i el percentatge de canvi en el nombre de dispositius en comerços i espais recreatius, desagregats pel nivell d’ingressos dels **comtats**. El període analitzat està comprès entre el gener de 2020 i l’abril de 2020 i la metodologia d’anàlisi utilitzada pels autors ha estat un model de panel de dades amb efectes fixos. Els principals resultats que troben els autors mostren que el distanciament social generat després que es declarés l’estat d’emergència en cadascun dels diferents estats als quals pertanyen els comtats està substancialment diferenciat segons el nivell d’ingressos dels comtats. Per al quintil superior d’ingressos, després de la declaració d’emergència, el percentatge de dispositius que es queden completament a casa es redueix a la meitat, igual que la distància mitjana recorreguda fora de casa i el percentatge de canvi en el nombre de dispositius en comerços i espais recreatius.

En segon lloc, i també per al cas dels **Estats Units**, trobem el treball de Lou et al. [-@Lou2020], que fa una anàlisi comparativa **per comtats** sobre la resposta a la mobilitat després de la declaració d’emergència entre els grups d’ingressos més baixos i el grup d’ingressos més alts. A diferència del treball de Weill et al. [-@Weill2020], aquest treball també incorpora dades de mobilitat referents a si els desplaçaments s’han fet per motius laborals o no i el nombre de desplaçaments en transport públic. L’horitzó temporal analitzat en l’estudi està comprès entre l’1 de gener de 2020 i el 15 d’abril de 2020. La metodologia d’investigació utilitzada ha estat un model de diferències en diferències. Els resultats que troben els autors en relació amb el percentatge d’individus que es queden a casa, nombre de viatges fets per individu i quantitat de milles recorregudes per individu després de la declaració d’emergència, van en la línia dels que troba Weill et al. [-@Weill2020]. L’impacte de la directriu sobre la mobilitat genera menys efecte en el grup d’ingressos més baixos que en el grup d’ingressos més alts. Referent a l’impacte de la directriu segons si els desplaçaments són per motius laborals o no, els autors observen que per als desplaçaments relacionats amb la feina, i per al grup d’ingressos més baixos, la directriu no fa reduir significativament els viatges realitzats. En canvi, per als viatges que no estan relacionats amb motius laborals, i per al grup d’ingressos mitjans i alts, la directriu redueix significativament el nombre de viatges realitzats. Amb relació al nombre de desplaçaments en transport públic, els resultats mostren que després d’emetre’s la directriu el grup d’ingressos més baixos incrementa el nombre de vistes al mateix. 

Més recentment i també per al cas dels **Estats Units**, trobem el treball de Huang et al. [-@Huang2021], que analitza les disparitats en la dinàmica de la mobilitat entre els **comtats** amb ingressos més baixos i els comtats amb ingressos més alts a partir de l’elaboració d’un índex de resposta a la mobilitat. El període analitzat en el treball va de l’1 de març de 2020 al 30 de juny de 2020. Les dades de mobilitat inclouen la distància màxima diària recorreguda per un usuari, el nombre de sol·licitud de navegació per a la categoria conducció, el nombre de desplaçaments al lloc de treball i la distància recorreguda per geoetiquetatge de tuits. La metodologia d’investigació utilitzada en l’anàlisi està basada en l’anàlisi exploratòria de dades. Els resultats que troben els autors mostren una correlació positiva entre l’índex de resposta per comtats i la renda mitjana del comtat. Els comtats amb menys ingressos presenten un índex de resposta a la mobilitat negatiu (els canvis de mobilitat durant la pandèmia i l’escenari de referència són més petits) i els comtats amb més ingressos, un índex de resposta a la mobilitat positiu (els canvis de mobilitat durant la pandèmia i l’escenari de referència són més grans). Les diferents variables de mobilitat utilitzades confirmen que la resposta a la mobilitat ha sigut diferent segons el nivell d’ingressos del comtat. El $20\%$ dels comtats més rics reaccionen d’una manera més agressiva a la reducció de la mobilitat en comparació al $20\%$ dels comtats més pobres. 

Finalment, i també per al cas dels **Estats Units**, trobem el treball de Kim i Kwan [-@Kim2021], que analitza l’impacte de la pandèmia en la mobilitat **per comtats** associats al partidisme polític, la pobresa i les polítiques de restricció a la mobilitat. En aquest treball, a diferència dels anteriors, l’horitzó temporal de l’estudi comprèn de l’1 de març de 2020 al 30 de setembre de 2020, incloent-hi així tant la primera onada com la segona onada de restriccions. La metodologia emprada per portar a terme l’anàlisi ha estat un model de panel de dades amb efectes fixos. Amb relació a la variable partidisme, els autors mostren que, durant el període de recuperació de la mobilitat (d’abril a juny), els comtats demòcrates es van desplaçar menys que els republicans i que les polítiques de restricció a la mobilitat únicament van tenir efecte durant els primers dos mesos de la primera onada. Referent a l’anàlisi dels efectes de la mobilitat sobre la pobresa, els autors mostren que, durant el primer període de la primera onada, els comtats amb un percentatge més alt de persones pobres redueixen menys la mobilitat que els comtats amb un percentatge més baix de persones pobres. En canvi, quan la mobilitat es comença a recuperar (segon període de la primera onada), els comtats amb un percentatge més alt de persones pobres redueixen més la mobilitat que els comtats amb un percentatge més baix de persones pobres.

## Impactes distributius dels efectes de la pandèmia en la mobilitat en l’àmbit urbà

Per al cas dels **Estats Units**, en primer lloc trobem el treball d’Iio et al. [-@Iio2021], que analitza els impactes distributius de la pandèmia en la mobilitat en l’**àrea metropolitana de Houston** a través de les variables distància total del viatge, el radi de gir, el nombre de llocs diferents visitats i la distància recorreguda per viatge. El període analitzat en el treball va del gener de 2020 a l’abril de 2020. La metodologia d’anàlisi està basada en l’anàlisi exploratòria de dades. Els principals resultats del treball mostren que l’abril de 2020 hi ha una forta correlació negativa entre el nivell d’ingressos de la població i la distància total del viatge, el radi de gir i el nombre de llocs diferents visitats. Amb pandèmia, els individus amb nivells de renda més alts són els que més van reduir la mobilitat. De fet, per a les rendes situades entre 20.000-30.000 dòlars la distància total del viatge es va reduir un $54\%$, el radi de gir un $63\%$ i el nombre de llocs diferents visitats un $44\%$. En canvi, per a les rendes situades entre 70.000-80.000 dòlars, la distància total del viatge es va reduir un $76\%$, el radi de gir un $90\%$ i el nombre de llocs diferents visitats un $54\%$.

En segon lloc, i també per al cas dels **Estats Units**, trobem el treball de Sy et al. [-@Sy2021], que analitza les disparitats en la mobilitat al metro de **Nova York** segons la renda mitjana dels diferents barris que conformen els districtes de Manhattan, Brooklyn, Queens i Bronx. L’horitzó temporal analitzat està comprès entre el 4 de gener de 2020 i l’11 d’abril de 2020. La metodologia d’anàlisi utilitzada està basada en un model de regressió lineal generalitzat. Els principals resultats del treball mostren que als barris on la renda mitjana és més elevada, la mobilitat també tendeix a reduir-se més. De fet, els barris on més es va reduir la mobilitat van ser el barri de Bushwick/Bedford Stuyvesant, ubicat al districte de Brooklyn, i el barri d’Upper West Side, al districte de Manhattan. En canvi, els districtes que van presentar una reducció més baixa de la mobilitat van ser el barri de Rockaway, ubicat al districte de Queens, seguit del barri Fort George, situat al districte de Manhattan. En el treball també es remarca que els barris on menys es va reduir la mobilitat presentaven un percentatge més alt de treballadors ocupats en sectors essencials i de persones no blanques/hispanes.

Per al cas d’**Espanya**, en primer lloc, trobem el treball de Checa et al. [-@Checa2020], que analitza el comportament de la mobilitat en el transport públic ferroviari en l’**àrea metropolitana de Barcelona** segons el nivell de renda mitjanade l’àrea on està ubicat l’accés. L’horitzó temporal analitzat correspon al període comprès entre l’1 de gener de 2020 i el 12 d’abril de 2020. Dintre d’aquest període, els autors distingeixen sis finestres temporals diferents: situació anterior a la pandèmia (gener i febrer de 2020), setmana prèvia al confinament (del 9 al 13 de març de 2020), primera setmana de confinament (del 16 al 20 de març de 2020), segona setmana de confinament (del 23 al 27 de març de 2020), tercera setmana de confinament (del 30 de març de 2020 al 3 d’abril de 2020) i quarta setmana de confinament (del 6 al 9 d’abril de 2020). La metodologia utilitzada en el treball està basada en l’anàlisi exploratòria de dades. Els principals resultats que troben els autors mostren que, durant els quatre períodes de confinament analitzats, la reducció de la mobilitat en les zones metropolitanes de renda més baixa ha sigut sempre inferior que la reducció de la mobilitat en les zones metropolitanes de rendes més altes. De fet, la setmana prèvia al confinament, i concretament el 12 de març de 2020, les zones metropolitanes de rendes més altes ja havien reduït la mobilitat un $12,3\%$ respecte a les dades anteriors a la pandèmia. En canvi, per a les zones metropolitanes de rendes més baixes, aquesta disminució va ser únicament de l’$1,6\%$. Aquests resultats també es confirmen per a l’anàlisi particular de la ciutat de Barcelona, on les reduccions de la mobilitat van ser més fortes als districtes més acomodats, com ara els de Sarrià-Sant Gervasi o les Corts; en canvi, la mobilitat es va mantenir superior als barris on les rendes són més baixes, com ara Nou barris, Sant Andreu i Sants-Montjuïc. 

En segon lloc, trobem el treball de Mejía-Donante et al. [-@Mejia2021], que també s’ha elaborat amb dades de mobilitat procedents de l’**àrea metropolitana de Barcelona**. El treball de Mejía-Donante et al. [-@Mejia2021] compara els patrons de mobilitat abans i després de la pandèmia sobre diverses variables socioeconòmiques, entre les quals hi ha el nivell d’ingressos de la població. La variable mobilitat utilitzada en l’estudi procedeix de la matriu de dades d’origen a destinació que elabora l’empresa NOMMON a partir del seguiment de dades de telèfons mòbils dels clients d’Orange entre 2019 i 2020. La metodologia d’investigació emprada ha estat un model lineal generalitzat utilitzant l’aproximació de la distribució binomial negativa. Els principals resultats que troben els autors mostren que, per a l’any 2020, els col·lectius amb ingressos més alts van reduir més la mobilitat que el grup d’ingressos més baixos. En canvi, els grups d’ingressos més baixos no van disminuir la mobilitat entre el 2019 i el 2020.

Més recentment, per al cas d’Espanya, també trobem el treball de Glodeanu et al. [-@Glodeanu2021], que analitza els diferencials de mobilitat durant i després del confinament en l’**àrea metropolitana de Madrid** a través de l’índex de privació (mesura que recull les característiques socioeconòmiques de la població i les resumeix en un grau de privació). Els autors han aproximat la variable mobilitat a través del percentatge de persones que durant el dia es desplacen fora de la seva zona de residència. L’horitzó temporal utilitzat en el treball s’ha dividit en quatre períodes: període de mesures més restrictives (del 30 de març de 2020 al 5 d’abril de 2020), la fase 1 (del 25 de maig de 2020 al 31 de maig de 2020), la fase 2 (del 8 de juny de 2020 al 14 de juny de 2020) i la nova normalitat (del 15 de juny de 2020 al 20 de juny de 2020). La metodologia d’investigació utilitzada en el treball ha estat l’anàlisi exploratòria de dades. Els principals resultats que troben els autors mostren que, durant el període de mesures més restrictives, un increment de l’índex de privació igual a 1 incrementava la mobilitat un $0,9\%$ en comparació amb les dades de novembre de 2019. Aquesta associació es va reforçar durant els següents tres períodes analitzats ($1,8\%$ en la fase 1, $1,3\%$ en la fase 2 i $1,6\%$ en el període de nova normalitat). 

Per a **Kenya**, trobem el treball de Pinchoff et al. [-@Pinchoff2021], que analitza els patrons de mobilitat a **Nairobi** en cinc dels barris més marginals de la ciutat: Kibera, Huruma, Kariobangi, Dandora i Mathare. A partir d’unes enquestes telefòniques fetes durant el mes de maig de 2020, els autors analitzen les dinàmiques de mobilitat segons la situació laboral dels individus, el nivell d’ingressos, el sexe i la percepció del risc en viatjar. Els autors categoritzen la variable mobilitat en tres classes: els que no van sortir de casa, els que es van moure pel barri i els que es van desplaçar fora del barri. La metodologia d’investigació utilitzada està basada en un model lògit multinomial. Els principals resultats que troben els autors indiquen que els individus que no van sortir de casa, comparat amb els individus que van reportar mobilitat pel barri, tenien més probabilitat de ser rics. Referent al gènere, el treball també mostra que les dones que no van sortir de casa, comparat amb les dones que van reportar mobilitat pel barri, estaven situades en el quintil de renda més ric. El grup de menys risc van ser els individus que no es van moure de casa, que eren principalment dones joves que havien perdut la feina i que residien a les llars amb els nivells de renda més alts. 

Finalment, a **Xile** trobem el treball de Carranza et al. [-@Carranza2020], que analitza els efectes del compliment del confinament en la mobilitat en l’**àrea metropolitana de Santiago de Xile** desagregat per nivell de rendes. La variable mobilitat utilitzada en l’estudi s’ha aproximat a través del nombre de desplaçaments que els individus han fet a fora de la seva residència. L’horitzó temporal està comprès entre el 2 de març de 2020 i el 3 de juliol de 2020. La metodologia d’investigació utilitzada en l’estudi està basada en un model de panel de dades amb efectes fixos. Els principals resultats que detecten els autors mostren que els municipis més rics presenten una reducció de la mobilitat més gran que els municipis que tenen unes rendes més baixes. De fet, la reducció de la mobilitat a les zones de renda alta oscil·la entre el $50\%$ i el $90\%$; en canvi, per a les zones de rendes baixes la reducció de la mobilitat oscil·la entre el $20\%$ i el $50\%$. 

## Conclusions 

La crisi sanitària provocada per la pandèmia de la COVID-19 ha tingut un gran impacte sobre la mobilitat i ha posat de manifest que no tots els individus han tingut les mateixes oportunitats per poder complir les mesures de confinament i distanciament social recomanades per les autoritats. Els treballs revisats en aquest capítol evidencien que la mobilitat en pandèmia ha generat una nova font de desigualtats, ja que els individus situats als nivells superiors de renda han pogut reduir més la mobilitat que els situats a l’extrem inferior. Un dels principals motius que explicarien aquestes disparitats en la mobilitat seria la capacitat de teletreballar. Els treballadors amb un nivell de renda més alt tenen més probabilitat de poder-se adaptar a la modalitat de teletreball que els situats en els trams més baixos de renda (Espinoza i Reznikova, [-@Espinoza2020]).

El principal problema de les desigualtats en la mobilitat durant la pandèmia és que els treballadors més pobres, a diferència dels més rics, acostumen a desplaçar-se amb un bé inferior, com és el cas del transport públic, i exposar-se a grans aglomeracions en moments de pandèmia quan les recomanacions són quedar-se a casa genera desigualtats. Els individus que durant la pandèmia no van poder reduir els desplaçaments i que van continuar utilitzant el transport públic per anar a treballar van estar molt més exposats a contreure el virus que els ocupats que estaven teletreballant o els que accedien a la feina mitjançant el vehicle privat. 

Tot i que cada vegada hi ha més estudis que indiquen que el risc de contreure la COVID-19 al transport públic és molt baix (UITP, [-@Uitp2020]), fins que el virus no estigui erradicat poden sortir noves variants que ens obliguin a extremar les mesures de seguretat. En cas d’un nou confinament, per tal de reduir les desigualtats es podria compensar els treballadors essencials que es desplacen en transport públic amb un complement salarial per perillositat laboral. 

També és important esmentar que les desigualtats en la mobilitat generades per la pandèmia podrien estar provocant  una externalitat negativa al conjunt de la societat. Si les classes treballadores que abans de la pandèmia es desplaçaven amb transport públic i que durant la pandèmia van canviar al vehicle privat, amb una situació de nova normalitat, continuen utilitzant el vehicle privat, els nivells de congestió i pol·lució a les grans ciutats es podrien veure afectats. En aquest cas, per tal d’evitar efectes permanents en la mobilitat és d’extrema necessitat la intervenció de les autoritats de transport i especialment en les grans conurbacions urbanes. Els plans de mobilitat urbana i sostenible (PMUS) de les ciutats s’haurien d’adaptar a aquesta nova normalitat. Fomentar una utilització més gran d’aparcaments d’enllaç o dissuasius amb tarifes progressives a les perifèries de les grans ciutats milloraria la mobilitat i ajudaria a reduir la contaminació en el nucli urbà. Els peatges de congestió també podrien ser una solució eficient per evitar embussos i reduir la contaminació; no obstant això, el cost polític d’aplicar aquesta mesura pot ser elevat. 

