# Col·laboradors {-}

**Daniel Albalate** és doctor en Economia per la Universitat de Barcelona i Màster en Economia per la University College London (Regne Unit). Actualment és el director de l’Observatori d’anàlisi i avaluació de les polítiques públiques de la Universitat de Barcelona i professor agregat del departament d’econometria, estadística i economia aplicada de la mateixa Universitat. És expert en polítiques de transport i d’infraestructures. És autor de més de 60 articles publicats en revistes científiques de prestigi internacional i autor de dos llibres sobre economia de les infraestructures de transport.

**Salvador Anton Clavé** és Catedràtic d'Anàlisi Geogràfica Regional a la Universitat Rovira i Virgili on és Investigador Principal del Grup de Recerca en Anàlisi Territorial i Estudis Turístics - GRATET. Els objectius de la seva activitat investigadora són l'anàlisi de l'evolució de les destinacions turístiques, la globalització de l'esbarjo i l'impacte dels parcs temàtics i les atraccions recreatives, el paper del turisme, les polítiques turístiques i la governança de les destinacions en el desenvolupament local i regional i la incidència de les tecnologies digitals en la transformació del turisme i el lleure.

**Paula Bel** és doctora en Economia per la Universitat de Barcelona i professora contractada doctora al Departament d’Empresa de la Universitat Abat Oliva CEU, on és directora de màsters i postgraus. La recerca de Paula Bel s’ha centrat en la col·laboració públic-privada, especialment en l’àmbit de les infraestructures de transport.

**Xavier Delclòs-Alió** és investigador postdoctoral al Departament de Geografia de la Universitat Rovira i Virgili. La seva recerca examina les mobilitats de la població a diferents nivells, amb un enfocament particular en els patrons de mobilitat urbana, la seva relació amb l'entorn construït i social, així com amb un especial èmfasi en la mobilitat activa i la seva relació amb l’activitat física.

**Xavier Fageda** és llicenciat i doctor en Ciències Econòmiques i Empresarials per la Universitat de Barcelona i màster en Economia per la Universitat de Warwick. Catedràtic d'economia aplicada a la Universitat de Barcelona, és especialista en temes de transport, organització industrial i avaluació de polítiques. Ha publicat diversos articles i ha liderat diversos projectes competitius i publicats capítols de llibre a editorials internacionals com Elsevier, Springer o Routledge.

**Oriol Gallardo Prat** és Investigador pre-doctoral al Grup de recerca d’anàlisi territorial i estudis turístics (GRATET) de la Universitat Rovira i Virgili. La seva recerca se centra principalment en estudiar la relació entre turisme i territori.

**Albert Gragera** és investigador postdoctoral a la Universitat Autònoma de Barcelona (María Zambrano). La seva recerca s’enfoca en l’àmbit de l’economia urbana, sobretot centrada en l’avaluació de polítiques de transport, la relació entre transport i urbanisme, així com el rol dels cotxes a les ciutats, en especial sobre la interacció de l’aparcament amb tot això. És Doctor en Economia per la Universitat de Barcelona i Màster d’Enginyeria Civil per la UPC-BarcelonaTECH. Prèvia incorporació a la UAB ha treballat en diverses universitats i centres de recerca, així com consultoria en l'àmbit europeu

**Aaron Gutiérrez** és Doctor en Geografia per la Universitat de Lleida. Professor Agregat del Departament de Geografia de la Universitat Rovira i Virgili, amb acreditació de Recerca Avançada (Catedràtic). Membre del Grup de Recerca d'Anàlisi Territorial i Estudis Turístics (GRATET) de la URV. Ha estat investigador visitant a la London School of Economics, Pontificia Universidad Católica de Chile, Politecnico di Torino i Universitat París 8, entre d'altres. Els seus àmbits de recerca principals son la geografia urbana, els transports i la mobilitat sostenible. Ha dirigit diversos projectes de recerca nacionals. Actualment és l'investigador principal del projecte "Mobilitat dels visitants a la ciutat de Barcelona després de la COVID-19: anàlisi i orientacions pel foment d'una mobilitat social i ambientalment sostenible (VISITMOB)" finançant per la Fundació "La Caixa" i l'Ajuntament de Barcelona.

**Carlos León-Gómez** és candidat a PhD en economia per la Universitat de Barcelona i Màster en Anàlisi Econòmica per la Paris School of Economics (França). Actualment és consultor internacional per al Grup d'Infraestructura, APP i Garanties (IPG) del Banc Mundial, i la Divisió de Política Fiscal del Banc Interamericà de Desenvolupament, on ha col·laborat amb diferents governs del món en el maneig de riscos fiscals, el finançament d'infraestructura pública, impostos i despesa pública, entre d'altres temes de política fiscal.

**Anna Matas** és Catedràtica d'Economia Aplicada a la UAB i membre del Grup de Recerca en Economia Aplicada (GEAP) en el marc de la convocatòria SGR. La seva recerca s'ha desenvolupat principalment a l'àrea de l'economia del transport. Ha participat de manera continuada en projectes de recerca del Pla Nacional i actualment n'és investigadora principal. Els seus treballs s'han publicat a revistes com Transportation Research, Transport Policy, Regional Studies, Papers in Regional Science, Applied Economics i Energy Economics. Actualment dirigeix la línia d´Infraestructura i Transport de l´Institut d´Economia de Barcelona (IEB).

**Verónica Mejía Juárez** és Doctora en Geografia per la Universitat Autònoma de Barcelona (2020), arquitecta i enginyera en Gestió Ambiental (Equador, 2012, 2015) Ha treballat com a consultora a la redacció de plans territorials i urbanístics (Equador). Ha desenvolupat la recerca doctoral en temes vinculats als processos d'urbanització emprant com a eina base les imatges satel·litàries nocturnes. A més, ha desenvolupat projectes relatius a la mobilitat turística, dinàmica residencials, desigualtats energètiques com a part de grups de recerca de la UAB, la UB i la URV.

**Daniel Miravet** és doctor en Economia per la Universitat Rovira i Virgili (URV). Des de l’any 2009 treballa a l'Autoritat Territorial de la Mobilitat (ATM) del Camp de Tarragona, on actualment ocupa el lloc de responsable de mobilitat, estudis i sostenibilitat. També és professor associat del Departament d’Economia de la URV. Les seves àrees d’expertesa són la mobilitat i el transport públic, i en particular, la mobilitat turística.  

**Jordi Perdiguero** és Professor agregat del Departament d’Economia Aplicada de la Universitat Autònoma de Barcelona (UAB), membre del Grup de Recerca en Economia Aplicada (GEAP) i del Institut d’Economia de Barcelona (IEB). Les seves principals línies d’investigació han sigut la Economia del Transport i la Economia Energètica, publicant més de 25 articles científics a revistes JCR.

**Jordi Rosell** és professor lector d'economia Serra Hunter a la Universitat de Girona. És llicenciat en Economia per la Universitat Pompeu Fabra i en Ciències Ambientals per la Universitat de Barcelona. És doctor en economia per la Universitat de Barcelona amb una tesis doctoral sobre polítiques de transport i medi ambient, àmbits d'interès de la seva recerca actual.

**Josep Tomàs-Porres** és doctorand al Departament d'Economia de la Universitat Rovira i Virgili (URV). És llicenciat en Economia (2020) i Màster en Mercats Internacionals (2021), tots dos per la Universitat Rovira i Virgili (URV). Va començar la seva tesi el desembre de 2021, el seu principal focus d'anàlisi és la interacció entre la conducta innovadora, el comerç i el potencial transformador de les empreses. A més, també ha realitzat recerca en l'àmbit del transport i el turisme.
