--- 
title: "Els impactes de la Covid-19 en la Mobilitat i les seves conseqüències socials i econòmiques: Una revisió acadèmica internacional després de 2 anys de pandèmia"
author: "Daniel Albalate (Editor)"
date: "Oct-2022"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "Aquest projecte pretén entendre les causes i determinants dels canvis en les preferències i comportaments dels ciutadans de les grans àrees urbanes de Catalunya per tal d’identificar mesures i accions que puguin incidir-hi i mitigar o fins i tot revertir els efectes de la Covid19 sobre la sostenibilitat financera del transport públic i la sostenibilitat ambiental i la lluita contra el canvi climàtic, així com discutir-ne la seva viabilitat, la seva efectivitat en relació a l’evidència internacional, i la seva contribució a la solució o mitigació d’aquests dos grans reptes de sostenibilitat"
---

# Pròleg {-}
La pandèmia de la COVID-19 (SARS-CoV2) ha afectat de forma contundent la mobilitat en les grans àrees urbanes del món. A part de l’impacte de les restriccions imposades per les autoritats durant el confinament de la primavera de 2020, les dades apunten que la pandèmia podria haver produït canvis estructurals en les preferències i eleccions dels ciutadans a l’hora de moure’s diàriament. D’una banda, el teletreball, l’atur i altres restriccions d’activitat, així com la cautela de la ciutadania, han fet disminuir el conjunt de la mobilitat en les grans àrees urbanes, també de Catalunya. D’altra banda, la mobilitat ha patit un canvi significatiu quant a l’elecció del mode amb què es viatja, ja que s’evidencia una caiguda pronunciada de l’ús del transport col·lectiu, especialment dels modes públics, a la vegada que s’entreveu un increment de la mobilitat privada. Aquest fet genera una pressió afegida sobre dos reptes a llarg termini de les grans ciutats i àrees metropolitanes. En primer lloc, posa en risc la sostenibilitat del finançament del transport públic, tan rellevant per assolir l’eficiència i l’equitat en les economies urbanes. El manteniment, o fins i tot l’ampliació, dels serveis i de la qualitat requereix una participació creixent del pressupost públic davant de la davallada de la recaptació provinent dels usuaris, cosa que pressiona encara més el dèficit i la sostenibilitat del sistema. 

En segon lloc, els canvis en les preferències de mobilitat dels ciutadans i els seus efectes en l’elecció cap a modes menys sostenibles, especialment en la mobilitat metropolitana (a diferència de la urbana), reverteixen alguns dels guanys que s’havien assolit en els darrers anys —de major conscienciació en l’ús d’una mobilitat més sostenible— i renoven la pressió sobre la mobilitat sostenible i la lluita contra el canvi climàtic en les grans conglomeracions urbanes. 

En efecte, la pandèmia ha posat de manifest la interrelació entre la crisi climàtica, la mobilitat i la salut pública, i per tant la connexió entre una pandèmia sanitària com la de la COVID-19 i una pandèmia climàtica amb múltiples efectes negatius com és la del canvi climàtic. En la fase 0 i amb un relaxament inicial de les mesures més restrictives a Barcelona i a la seva àrea metropolitana, el trànsit va tenir una reducció propera al 60 % respecte del trànsit habitual d’abans del confinament. En els accessos va baixar un 62,7 %, mentre que a l’interior de la ciutat va disminuir un 60,7 % i a les Rondes, un 51,8 %. Per contra, el nombre d’usuaris del transport públic va caure un 85 % al metro i un 88 % a l’autobús, respecte del mateix període laborable previ al confinament. Aquesta asimetria en la caiguda de la mobilitat ja apuntava una reducció de la demanda explicada, principalment per les restriccions de l’activitat (sobretot cultural, esportiva i de lleure), pel teletreball, l’atur i la falta de turisme, com a conseqüència de les mesures de prevenció dels contagis. En canvi, el trànsit privat va experimentar una recuperació més marcada, amb una disminució de només el 22 % respecte d’un dia habitual. 

Si bé el confinament, el teletreball i les restriccions de mobilitat van tenir efectes beneficiosos sobre la qualitat de l’aire a Barcelona, la recuperació d’una certa normalitat, amb la tornada a la feina i a les escoles, va mostrar una tendència ben oposada. Aquest fet és preocupant, ja que el trànsit motoritzat és la principal font de contaminació atmosfèrica, molt especialment pel que fa a partícules de diàmetre inferior o iguals a 2,5 mm (PM2,5) i de diòxid de nitrogen (NO2). Les conseqüències de revertir els avenços que s’havien assolit a causa de més conscienciació en l’ús d’una mobilitat més sostenible, són conegudes i tenen a veure molt directament amb la salut pública i la qualitat de vida a les ciutats. De fet, els nivells de qualitat de l’aire s’han situat de nou per sobre de les recomanacions de l’Organització Mundial de la Salut (OMS), fins i tot en moments en què no s’havia assolit encara una reobertura total de l’economia. Aquest fenomen no és nou; podem fer referència als efectes d’atacs terroristes (9S Nova York; 11M Madrid; Londres 2005) sobre les eleccions de mobilitat. En aquests casos, el transvasament modal del transport públic cap al vehicle privat ha significat habitualment un augment important dels nivells de pol·lució. 

Aquest biaix favorable a la mobilitat en vehicle privat, especialment en la mobilitat interurbana, es veu complementada en els viatges urbans per l’increment de l’ús de vehicles de mobilitat personal, com ara bicicletes —amb un increment del 96 % el maig de 2020 respecte del mes de maig de 2019, a Barcelona—, patinets o plataformes de manillar (segways), així com els viatges a peu, que competeixen directament amb el transport públic i en dificulten la sostenibilitat financera. 

L’impacte de la pandèmia sobre la mobilitat i sobre les pressions ja existents en la sostenibilitat del sistema de mobilitat podria haver estat fins i tot més greu sense la intervenció de les autoritats i els gestors del transport. A Barcelona, per exemple, les autoritats han promogut canvis en els serveis de transport públic. Entre aquests canvis, destaca l’augment de la capacitat, especialment en les línies de metro més denses, per esponjar i facilitar l’espai entre usuaris, fent ús de tots els vehicles disponibles en hora punta i optimitzant les freqüències. A més, TMB ha posat a disposició dels usuaris una aplicació que mostra indicadors de l’ocupació mitjana estimada al metro i autobusos. 

Per altra banda, s’han pres mesures de recuperació de l’espai públic, amb la pacificació del trànsit amb les zones 30 (a Tarragona, per exemple) i amb l’eliminació d’aparcaments a la calçada, per tal de facilitar l’activitat a l’aire lliure i la mobilitat amb modes no motoritzats (a Barcelona). A això se li han sumat mesures de regulació del vehicle privat i de l’incentiu al transport col·lectiu, entre les quals convé ressaltar la implantació del carril bus-VAO a la C-31 en l’accés a la ciutat de Barcelona, la regulació de l’aparcament gratuït que encara quedava als carrers de Barcelona i els canvis de preus implementats allà on ja hi havia una regulació. Cal apuntar, finalment, que els efectes de la pandèmia sobre la mobilitat no són exclusius de Catalunya i les seves ciutats. 

Tots els estudis preliminars o publicats recentment en l’àmbit internacional mostren com la distància social seria la mesura de salut pública que hauria afavorit una caiguda en l’ús del transport col·lectiu (amb les conseqüències corresponents en termes de teletreball, restriccions d’activitats, etc.). I aquesta caiguda s’hauria agreujat amb la percepció d’alt risc de contagi dels usuaris, que opten arreu per limitar la seva mobilitat o s’inclinen per modes de transport individuals, en lloc de col·lectius. Entre aquests modes de transport individuals destaquen els vehicles a motor i els vehicles de mobilitat personal, com també passa a Catalunya. De fet, la venda d’aquests vehicles va experimentar un repunt que confirmaria que els efectes de la pandèmia sobre l’elecció modal, lluny de ser a curt termini i conjunturals, podrien afectar la mobilitat i les preferències dels usuaris a llarg termini. 

Aquesta monografia pretén aportar dues contribucions a la literatura. En primer lloc, procura aglutinar i revisar la literatura científica que ha tractat els efectes de la pandèmia sobre diferents aspectes de la mobilitat. L’objectiu no és altre que sintetitzar el coneixement que ha assolit la comunitat científica sobre les qüestions relatives a la mobilitat durant la pandèmia i el període posterior. Es tracta, doncs, no només de conèixer els impactes a curt termini, sinó també d’abordar els canvis estructurals amb caràcter permanent que puguin afectar la manera com ens movem i com gestionem la mobilitat a les grans ciutats. En la primera part de la monografia, s’hi poden trobar articles temàtics elaborats per acadèmics catalans que treballen i fan recerca en l’àmbit de la mobilitat. En segon lloc, en aquesta obra també s’inclouen els primers resultats d’una enquesta elaborada a més de 8.000 residents de les àrees urbanes de Barcelona, Girona i el Camp de Tarragona sobre la seva mobilitat en el context de la pandèmia i de la postpandèmia. Aquesta primera anàlisi de les dades de l’enquesta ens ajuda a entendre millor els impactes de la pandèmia, sobre la mobilitat a les grans àrees urbanes de Catalunya, a curt i llarg termini. Tant l’enquesta com la monografia han rebut finançament de la convocatòria Pandèmies 2020 de la Secretaria General de Recerca de la Generalitat de Catalunya. Es tracta d’un projecte en què han participat més de 20 investigadors de fins a set universitats catalanes, que ha estudiat els efectes de la pandèmia en la sostenibilitat financera i ambiental de la mobilitat en les grans àrees urbanes de Catalunya. 

La monografia s’estructura. En el primer capítol ha estat elaborat per Anna Matas i Jordi Perdiguero, de la Universitat Autònoma de Barcelona, que examinen els impactes de la pandèmia en el transport públic col·lectiu. El segon capítol tracta també l’efecte del transport públic, però fent èmfasi en les zones turístiques i de baixa densitat. És un capítol elaborat per Aaron Gutiérrez, Daniel Miravet i Xavier Delclòs-Alió, de la Universitat Rovira i Virgili. Xavier Fageda i Carlos León-Gómez, de la Universitat de Barcelona, canvien el focus en el tercer capítol i estudien el cas de la mobilitat privada. El quart capítol està dedicat a la micromobilitat (principalment vehicles de mobilitat personal), i ha estat escrit per Daniel Albalate i Carlos León-Gómez, també de la Universitat de Barcelona. En el cinquè capítol, Albert Gragera, de la Universitat Autònoma de Barcelona, analitza el paper del teletreball i dels canvis residencials, mentre que Jordi Rosell, de la Universitat de Girona, tracta la relació de la mobilitat amb la qualitat de l’aire en el sisè capítol. Pel seu costat, Paula Bel, de la Universitat Abat Oliva, posa el focus sobre la desigualtat en el setè capítol i Xavier Delclòs-Alió, Aaron Gutiérrez, Josep Tomàs-Porres, Oriol Gallardo, Daniel Miravet, Salvador Anton Clavé, sobre la relació entre mobilitat i salut, en el vuitè capítol. Finalment, el novè capítol és el que analitza els resultats de l’enquesta feta en el marc del projecte de recerca Pandèmies 2020. El capítol ha estat elaborat per Verónica Mejía, Aarón Gutiérrez y Xavier Delclòs-Alió, tots vinculats a la Universitat Rovira i Virgili. 

Esperem que aquest monogràfic pugui aportar llum sobre els impactes locals d’aquest fenomen global i ajudar a dissenyar millors polítiques públiques de mobilitat a casa nostra.


**Daniel Albalate**

**Barcelona, Octubre de 2022**



```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
